### ISSUE TITLE
Icons are too big - Waybar Tray

### ISSUE THREAD

**Issue by trmendes** [Alexays/Waybar#1233] opened 2021-09-03 05:24 UTC
Not sure if I'm doing something wrong but, once in a while Waybar will load with some huge icons on tray

> config

```
{
    "layer": "top",
    "position": "top",
    "height": 24,

    "modules-left": ["sway/workspaces", "sway/mode"],
    "modules-center": [],
    "modules-right": [
    "tray",
    "network",
    "backlight",
    "pulseaudio",
    "battery",
    "custom/weather",
    "idle_inhibitor",
    "clock",
    "sway/language",
    "custom/em_group_b"
    ],

    "sway/mode": {
        "format": " {}"
    },
    "sway/workspaces": {
        "format": "{name}",
        "disable-scroll": true
    },
    "sway/window": {
        "max-length": 80,
        "tooltip": false
    },
    "clock": {
        "format": "{:%a %d %b %H:%M}",
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "format-alt": "{:%Y-%m-%d}"
    },
    "battery": {
        "format": "{icon}",
        "format-icons": ["💚🖤🖤🖤🖤", "💚💚🖤🖤🖤", "💚💚💚🖤🖤", "💚💚💚💚🖤", "💚💚💚💚💚"],
        "format-charging": "⚡ {icon} {capacity}%",
        "format-discharging": "🔦 {icon} {capacity}%",
        "interval": 120,
        "states": {
            "warning": 25,
            "critical": 10
        }
    },
    "network": {
        "format": "{icon} {signalStrength}%",
        "format-alt": "{ipaddr}/{cidr} {icon}",
        "format-icons": {
            "wifi": [""],
            "ethernet": ["🛤️"],
            "disconnected": ["🥸"]
        },
        "tooltip-format-wifi": "{essid} - {signalStrength}%",
        "format-alt": "{ifname}: {ipaddr}/{cidr}"
    },
    "pulseaudio": {
        "format": "{icon} {volume}%",
        "format-muted": "🔇",
        "format-icons": {
            "phone": ["🎧🔈", "🎧🔉", "🎧🔉", "🎧🔊"],
            "default": ["🔈", "🔉", "🔉", "🔊"]
        },
        "scroll-step": 10,
        "on-click": "pavucontrol"
    },
    "backlight": {
        "format": "{icon} {percent}%",
        "format-icons": ["💡"],
        "on-scroll-down": "light -A 10%",
        "on-scroll-up": "light -U 10%"
    },
    "idle_inhibitor": {
        "format": "{icon}",
        "format-icons": {
            "activated": "",
            "deactivated": ""
        }
    },
    "tray": {
        "icon-size": 24,
        "spacing": 1,
    },
    "custom/em_group_b": {
        "format": " 🌳 🥑 🌈",
    },
    "custom/weather": {
        "format": "{}",
        "interval": 600,
        "return-type": "json",
        "exec": "sh ~/.config/waybar/modules/weather.sh"
    },
    "sway/language": {
        "format": "{}",
        "on-click": "swaymsg 'input * xkb_switch_layout next'",
        "max-length": 50
    }
}
```
> style.css

```
* {
    border:        none;
    border-radius: 0;
    font-family:   Monospace, FontAwesome;
    font-size:     16px;
    box-shadow:    none;
    text-shadow:   none;
    transition-duration: 0.20s;
    min-height: 0;
}

window#waybar {
    background: #282A36;
    color:      #F8F8F2;
}

#workspaces {
    margin: 0 5px;
}

#workspaces button {
    background: #282A36;
    color:      #F8F8F2;
    padding:    0 5px;
}

#workspaces button:hover {
    background: #282A36;
    border-top: 3px solid #6272A4;
}

#workspaces button.focused {
    color:      #F1FA8C;
    border-top: 3px solid rgba(245, 128, 50, 1);
}

#workspaces button.urgent {
    color:      #FF5555;
}

#mode, #tray, #battery, #cpu, #memory, #network, #pulseaudio, #idle_inhibitor, #backlight, #mpd, #custom-weather {
    margin:     2px 5px 2px 5px;
}

#mode {
    color:      #FF5555;
}

#clock {
    margin:     0px 5px 0px 5px;
}

#battery.warning {
   color:       #FFA500;
}

#battery.critical {
    color:      #FF5555;
}

#battery.charging {
    color:      #F8F8F2;
}

#battery.full {
    color:      #50FA7B;
}

#tray > .passive {
    -gtk-icon-effect: dim;
}

#tray > .needs-attention {
    -gtk-icon-effect: highlight;
    background-color: #eb4d4b;
}

#idle_inhibitor {
    background-color: #2d3436;
}

#idle_inhibitor.activated {
    color: #eb4d4b;
}

#custom-icon-cube {
  margin: 0px 2px;
  padding: 0.5rem 0.9rem;
  /*color: #d8dee9;*/
  /*background: #2e3440;*/
  color: #2e3440;
  background: #f2bb9a;
  border-radius: 0.4rem;
}

#custom-icon-cube {
  /*background: #d8dee9;*/
  color: #282a36;

  /* pride month */
  background: linear-gradient(
    180deg,
    #f00000,
    #f00000 16.67%,
    #ff8000 16.67%,
    #ff8000 33.33%,
    #ffff00 33.33%,
    #ffff00 50%,
    #007940 50%,
    #007940 66.67%,
    #4040ff 66.67%,
    #4040ff 83.33%,
    #a000c0 83.33%,
    #a000c0
  );
}
```

![sway-2021-09-03-051939](https://user-images.githubusercontent.com/16507629/131954713-f12d3bbb-09e9-491a-a996-33bbc5ad07a5.png)

**Comment by tmarkov** [comment] 2021-09-06 11:47
I can confirm. I'm on a HIDPI display, and would assume that has something to do with the issue - are you as well?

**Comment by trmendes** [comment] 2021-09-06 12:45
HIDPI display! 

It is very random and, those bellow are the combinations I get:

* Big icons only
* Big icons and small icons
* Small icons only

**Comment by minhduc0711** [comment] 2021-09-07 09:17
Hmm, this is supposed to be fixed by https://github.com/Alexays/Waybar/pull/1211. Are you using the latest version?

**Comment by trmendes** [comment] 2021-09-07 09:19
```
Waybar v0.9.8
```

**Comment by minhduc0711** [comment] 2021-09-07 09:31
Use the git version https://aur.archlinux.org/packages/waybar-git/

**Comment by draptik** [comment] 2021-11-16 18:10
I also have this issue: some icons increase the height of waybar.
My waybar configs are here:
https://github.com/draptik/dotfiles/tree/master/.config/waybar

![image](https://user-images.githubusercontent.com/313058/142041286-dabf357f-b7a6-4c9d-9a24-7991a806e6e3.png)

**Comment by layus** [comment] 2021-12-14 19:32
Adding some more observations on this one: I also have mixed icon size on sway reload (which pkill's waybar and restarts a new instance). It turns out that the icons get back to their normal size after some time. My current theory is that it happens when the icon changes, like when the network WiFi signal changes strength, or a notification appears/disappears in slack. For icons that do not change, killing and restarting the related app creates a new icon in the right format.

I can only surmise that there is some initialization issue, or a kind of race condition that allows to create too big images during startup, and that later pixbufs are created correctly.

**Comment by lilydjwg** [comment] 2021-12-15 03:27
Recent experiences from me: *sometimes* when I start waybar when there are some icon in the tray (Telegram to be specific), it's large. If I quit the application and start waybar, and then start the application, the icon size is normal.

**Comment by tmpm697** [comment] 2022-03-08 17:09
I had same issue with `alacritty`'s icon, turn out it's `waybar` decides to display icon and it's big: https://github.com/alacritty/alacritty/issues/5939

**Comment by Alexays** [comment] 2022-10-27 06:52
Should be fixed now

**Closed by Alexays** 2022-10-27 06:52 UTC
