### ISSUE TITLE
Waybar crashes after outputs change

### ISSUE THREAD

**Issue by Difrex** [Alexays/Waybar#264] opened 2019-04-15 07:30 UTC
Hi,
The Waybar always crashes under the Sway after I change outputs without full config reload.
How to reproduce:
* Set single output
* Change outputs config via
  ```
  swaymsg output eDP-1 disable \
  output HDMI-A-2 pos 0 0 enable \
  output DP-1 pos 1920 0 enable
  ```
  or smth like this
* ...
* Got a segfault

The Waybar version is `Waybar v0.5.1 (Apr 10 2019, branch 'master')`

Also, the backtrace is:
```
#0  0x0000563a6b72938a in  ()
#1  0x0000563a6b709d51 in  ()
#2  0x00007f395ba566d0 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#3  0x00007f395ba560a0 in ffi_call () at /usr/lib/libffi.so.6
#4  0x00007f395c7891ac in g_cclosure_marshal_generic () at /usr/lib/libgobject-2.0.so.0
#5  0x00007f395c77ee75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#6  0x00007f395c76bfd5 in  () at /usr/lib/libgobject-2.0.so.0
#7  0x00007f395c772ce0 in g_signal_emitv () at /usr/lib/libgobject-2.0.so.0
#8  0x0000563a6b72a805 in  ()
#9  0x00007f395c803172 in  () at /usr/lib/libgio-2.0.so.0
#10 0x00007f395c822b0a in  () at /usr/lib/libgio-2.0.so.0
#11 0x00007f395c691661 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#12 0x00007f395c693739 in  () at /usr/lib/libglib-2.0.so.0
#13 0x00007f395c6946d2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#14 0x00007f395cc9f94f in gtk_main () at /usr/lib/libgtk-3.so.0
#15 0x0000563a6b6d2b7f in  ()
#16 0x0000563a6b6d17af in main ()
```

**Comment by Alexays** [comment] 2019-04-15 08:16
Similar to #160 #235,
The problem is that i can't replicate the issue with my external monitor :/

**Comment by Difrex** [comment] 2019-04-15 08:30
It reproduces only with two external monitors after switching from the laptop screen to the external two monitors with disabling internal screen. If I changing the outputs to one external monitor like this,
```
output eDP-1 pos 1920 0 scale 1.4 enable
output HDMI-A-2 pos 0 0 enable
output DP-1 disable
```
all working fine.

**Comment by Alexays** [comment] 2019-04-15 09:43
Can you try with latest commit d05b8398fa98b988af7e5fcad80a7aedc6112bf1
I just figured out why it crashes sometimes, but it may not be the same problem, when no window is open gtk exit by itself, now I force it to stay open to avoid this pb

**Comment by Difrex** [comment] 2019-04-15 10:56
Still crashes :(

**Comment by ranisalt** [comment] 2019-04-15 16:26
I did experience it a few times, but since my waybar is restarted by systemd it does not annoy. But definitely happens, I don't know the exact circumstances.

**Comment by Difrex** [comment] 2019-04-15 17:27
Can you share the systemd waybar unit?

**Comment by ranisalt** [comment] 2019-04-15 18:21
Sure!

```
[Unit]
Description=Highly customizable Wayland bar for Sway and Wlroots based compositors.
Documentation=https://github.com/Alexays/Waybar/wiki/
PartOf=graphical-session.target

[Service]
ExecStart=/usr/bin/waybar
Restart=always
RestartSec=3

[Install]
WantedBy=sway-session.target
```

**Comment by Difrex** [comment] 2019-04-16 07:01
Thank you! This workaround works.

**Comment by Alexays** [comment] 2019-04-17 17:28
@Difrex Can you test if without any modules the issue still persist :)

**Comment by Difrex** [comment] 2019-04-18 14:20
I was tried this with simple config:
```
{
    "layer": "top",
    "position": "top",
    "modules-left": [
        "sway/workspaces",
        "sway/mode"
    ],
    "tray": {
        "icon-size": 20
    }
}
```

And all working fine.

**Comment by Alexays** [comment] 2019-04-19 15:06
Ok so it's a duplicate of #160 and #242

**Comment by Alexays** [comment] 2019-04-23 13:57
Fixed with 90d89fe9742fec690677fc6965d28b25df8fc14f

**Closed by Alexays** 2019-04-23 13:57 UTC
Labels: bug

**Comment by Difrex** [comment] 2019-04-23 14:04
Thank you!

**Comment by alxchk** [comment] 2021-05-20 14:58
Looks like problem is still there.

```
Couldn't map window 0x563a3f656760 as subsurface because its parent is not mapped.
[2021-05-20 17:10:20.046] [warning] Requested height: 17 exceeds the minimum height: 18 required by the modules
[2021-05-20 17:10:20.046] [info] Bar configured (width: 1920, height: 18) for output: DP-5
[2021-05-20 17:10:20.263] [info] Bar configured (width: 1920, height: 17) for output: DP-5
[2021-05-20 17:10:23.088] [warning] Requested height: 17 exceeds the minimum height: 18 required by the modules
[2021-05-20 17:10:23.088] [info] Bar configured (width: 1920, height: 18) for output: DP-5
[2021-05-20 17:10:24.421] [info] Bar configured (width: 1920, height: 17) for output: DP-5
[2021-05-20 17:10:24.735] [warning] Requested height: 17 exceeds the minimum height: 18 required by the modules
[2021-05-20 17:10:24.735] [info] Bar configured (width: 1920, height: 18) for output: DP-5
[2021-05-20 17:10:24.851] [info] Bar configured (width: 1920, height: 17) for output: DP-5
[2021-05-20 17:12:58.008] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
[2021-05-20 17:12:58.133] [warning] Requested height: 14 exceeds the minimum height: 17 required by the modules
[2021-05-20 17:12:58.133] [info] Bar configured (width: 1920, height: 17) for output: eDP-1
terminate called without an active exception
waybar.service: Main process exited, code=killed, status=6/ABRT
waybar.service: Failed with result 'signal'.
waybar.service: Consumed 3min 12.201s CPU time.```

```
```
> waybar --version
Waybar v0.9.7
```

**Comment by tomalexander** [comment] 2021-07-15 16:43
Also ran into this today. Same waybar version as alxchk

**Comment by skunkfox** [comment] 2021-08-01 15:42
I can also confirm this bug should be re-opened. I am also running v.0.9.7.

**Comment by itsfarseen** [comment] 2021-08-17 03:08
I just cloned master and found out that the issue is not present in v0.9.8.
