### ISSUE TITLE
[wireplumber] Crash on multiple displays / reconnecting

### ISSUE THREAD

**Issue by DemonInTheCloset** [Alexays/Waybar#1928] opened 2023-01-07 22:53 UTC
The wireplumber module causes waybar to crash when displaying the bar on multiple displays, or redisplaying the bar on a single display.

## Software versions

```console
$ wireplumber -v
wireplumber
Compiled with libwireplumber 0.4.13
Linked with libwireplumber 0.4.13
$ waybar -v
Waybar v0.9.16
$ river -version
0.2.0
```

## Minimal Config

```json
{ "modules-center": ["wireplumber"] }
```

## Output

When starting on two displays it crashes immediatly, also happens when connecting an external display:

```console
$ waybar
[2023-01-07 23:40:37.415] [info] Using configuration file /home/user/.config/waybar/config
[2023-01-07 23:40:37.415] [info] Using CSS file /etc/xdg/waybar/style.css
[2023-01-07 23:40:37.454] [info] Bar configured (width: 1920, height: 14) for output: eDP-1
E 23:40:40.741415               GLib (null):(null):(null): g_log_set_writer_func() called multiple times
zsh: trace trap (core dumped)  waybar
```

Setting the `output` to only be on `HDMI-A-1` crashes when reconnecting the display ('#' are comments):

```console
$ waybar
[2023-01-07 23:43:05.449] [info] Using configuration file /home/user/.config/waybar/config
[2023-01-07 23:43:05.449] [info] Using CSS file /etc/xdg/waybar/style.css
# Connect HDMI cable
[2023-01-07 23:43:08.566] [info] Bar configured (width: 1360, height: 14) for output: HDMI-A-1
# Disconnect HDMI cable
[2023-01-07 23:43:17.768] [info] Bar removed from output: HDMI-A-1
# Connect HDMI cable
E 23:43:20.469875               GLib (null):(null):(null): g_log_set_writer_func() called multiple times
zsh: trace trap (core dumped)  waybar
```

**Comment by smoak** [comment] 2023-01-13 00:04
Looks to be a duplicate of https://github.com/Alexays/Waybar/issues/1852

**Comment by Alexays** [comment] 2023-01-13 13:00
Yes, dups of https://github.com/Alexays/Waybar/issues/1852

**Closed by Alexays** 2023-01-13 13:00 UTC
