### ISSUE TITLE
Network status doesn't update

### ISSUE THREAD

**Issue by pkillnine** [Alexays/Waybar#838] opened 2020-08-24 14:38 UTC
The network status module doesn't update when the network status changes.

**Comment by Hermitter** [comment] 2020-08-25 09:13
I have the same issue. Even with the default config file, I need to reload waybar to see any network changes.

**Comment by Hermitter** [comment] 2020-08-25 10:44
Seems like the new [release](https://github.com/Alexays/Waybar/releases/tag/0.9.3) has introduced a couple of bugs.

After downgrading from `0.9.3` to `0.9.1-1`, the network module is properly working again. It also solved a few issues with my custom modules.

**Comment by aqxa1** [comment] 2020-08-26 04:58
Possibly related issue. MPD stops updating its track status if you pause and then unpause. Same solution as above (downgrade to 0.9.1).

**Comment by MusiKid** [comment] 2020-08-30 21:48
I run a `git bisect` to try to find the faulty commit and it seems to be 6e7f22ac3ada6e27facee84fcbe2b3973eadbe1d. I didn't dig more but I suspect that the `epoll` loop wait indefinitely.

**Comment by accuminium** [comment] 2020-09-01 20:11
> I run a `git bisect` to try to find the faulty commit and it seems to be [6e7f22a](https://github.com/Alexays/Waybar/commit/6e7f22ac3ada6e27facee84fcbe2b3973eadbe1d). ~I didn't dig more but I suspect that the `epoll` loop wait indefinitely.~

I can confirm that the bug exists on current `master` (44119db436, which succeeds `0.9.3`) and that `git revert`ing 6e7f22a is sufficient to fix the problem.

**Comment by matt-della** [comment] 2020-09-14 14:32
Have there been any updates on this issue?

**Comment by ONDRA5** [comment] 2020-09-15 10:52
This issue still persists on waybar 0.9.3-3 (Arch Linux)

**Comment by matt-della** [comment] 2020-09-18 00:15
I'm surprised there hasn't been any activity on this. Given we've determined root cause (per the comment above), and that most computers running Waybar are presumably connected to some sort of network, I find it strange this isn't being treated a high priority bug. 
Obviously, it goes without saying that this software is phenomenal (and completely free), so here I am complaining about a thing I haven't paid a penny for, but I think it's still fair to consider this a fairly important bug to address.

**Comment by somini** [comment] 2020-09-20 20:03
Note that reverting 6e7f22a on the current master produces a conflict. I don't know enough about the module to resolve it.

**Comment by Alexays** [comment] 2020-09-21 08:40
@matt-della @somini 
By next week I'll look into it, sorry for the delay, I haven't had much time available lately.

**Comment by Alexays** [comment] 2020-09-21 08:57
Can someone tell me if this fixes the problem for them? @matt-della @somini @ONDRA5 
https://github.com/Alexays/Waybar/pull/861

**Comment by b10rn** [comment] 2020-09-21 09:27
https://github.com/Alexays/Waybar/pull/861 fixes the problem for me. Thank you.

**Comment by Alexays** [comment] 2020-09-21 10:10
Merged on master

**Closed by Alexays** 2020-09-21 10:10 UTC
Labels: bug

**Comment by somini** [comment] 2020-09-21 21:55
@Alexays Thanks for the fast turnaround.
