### ISSUE TITLE
Styles for `sway/window` do not work

### ISSUE THREAD

**Issue by crabvk** [Alexays/Waybar#3069] opened 2024-03-23 22:29 UTC
waybar: 10.0
sway: 1.9
wlroots: 17.1

I think the issue started with release of  waybar version 10.0. As [wiki](https://github.com/Alexays/Waybar/wiki/Styling) shows I use the style
```css
label#window {
    margin-left: 16px;
    color: #818384;
}
```
It worked with previous version, but now it doesn't.

**Comment by y0nei** [comment] 2024-03-23 23:49
Same issue for me but for `#workspaces button.persistent`

**Comment by crabvk** [comment] 2024-03-23 23:54
I've just noticed that the following styles work
```css
#window {
    margin-left: 16px;
}

#window > * {
    color: #818384;
}
```
So, maybe it's the wiki that needs to be updated.

**Comment by RobertMueller2** [comment] 2024-03-26 07:03
The OP issue was caused by 16aced7f9ffcac1200473192712575afaa4e6513. This added more flexibility by moving the classes from the label to the enclosing box, but it's a breaking change.

I've edited the debug output in https://github.com/Alexays/Waybar/wiki/Styling to reflect that. I didn't see any other references to label. I've also edited https://github.com/Alexays/Waybar/wiki/Module:-Sway to reflect the changed style hierarchy. @crabvk do you see any other places that are incorrect?

@y0nei the problem you are reporting must have a different cause.

**Comment by crabvk** [comment] 2024-03-26 08:25
Nope, don't see any other issues.

**Comment by RobertMueller2** [comment] 2024-06-30 20:02
@crabvk since #3086 was closed as well, and you didn't see any other issues, can you close this one, please? Thanks :)

**Closed** 2024-06-30 22:04 UTC
Labels: bug, sway
