### ISSUE TITLE
Clock shows tooltip despite ("tooltip": false,)

### ISSUE THREAD

**Issue by Pound-Hash** [Alexays/Waybar#1425] opened 2022-02-05 23:22 UTC
The clock's tooltip continues to appear even though I disabled it.

Config:
```
    "clock": {
		"tooltip": false,
    },
```

- Waybar 0.9.9-1

**Comment by opalvault** [comment] 2022-02-09 00:11
Can confirm, tooltip still shows up when "tooltip" is false on v0.9.9

**Comment by asahaf** [comment] 2022-02-20 16:40
tooltip still shows up when "tooltip" is false, even on v0.9.9

**Comment by LukashonakV** [comment] 2022-03-22 10:13
> tooltip still shows up when "tooltip" is false, even on v0.9.9

Waybar v0.9.12 - is not reproduced. Behavior is correct

**Comment by asahaf** [comment] 2022-03-22 11:06
The issue was fixed already

**Comment by LukashonakV** [comment] 2023-01-24 12:31
Hi @Pound-Hash, if the issue is solved can you close it please?

**Closed** 2023-01-24 12:35 UTC
Labels: bug
