### ISSUE TITLE
Focused workspace doesn't show workspace number

### ISSUE THREAD

**Issue by Kagukara** [Alexays/Waybar#2295] opened 2023-07-08 22:59 UTC
Version: Waybar v0.9.19
Last Updated: 2023-07-08 00:00 UTC [(https://archlinux.org/packages/extra/x86_64/waybar/)](https://archlinux.org/packages/extra/x86_64/waybar/)

After updating waybar the focused workspace no longer has its number and now looks like this:
![capture_2023-07-08_23-49-52](https://github.com/Alexays/Waybar/assets/43391109/c12de305-9460-4b3a-8be3-329e25e855fe)

When before it was like this:
![capture_2023-07-08_23-56-28](https://github.com/Alexays/Waybar/assets/43391109/10ed121a-063e-49a6-8abf-b5c2029bf619)

I have tried messing with the `#workspaces button.focused` part in my style.css but nothing has worked.

**Comment by ohdearaugustin** [comment] 2023-07-09 05:22
I can confirm the issue.

 Downgraded to 0.9.18 and the issues disappeared.

**Comment by dotfrag** [comment] 2023-07-09 11:05
I was about to post this. It seems to have been introduced by this change https://github.com/Alexays/Waybar/pull/2223/files:

```diff
-  std::vector<std::string> keys = {name, "urgent", "focused", "visible", "default"};
+  std::vector<std::string> keys = {"urgent", "focused", name, "visible", "default"};
```

Before this update, Urgent workspaces wouldn't show the urgent icon because `name` had higher priority. Now, `urgent` icon shows because it has the highest priority, but `name` doesn't show on `focused` workspace, because `focused` takes precedence. I believe the correct order would be:

```cpp
std::vector<std::string> keys = {"urgent", name, "focused", "visible", "default"};
```

**Comment by jcnafi** [comment] 2023-07-09 17:54
I use nerdfont icons. In my case workspace icon replaced by "focused" icon.

After update: [![up.png](https://i.postimg.cc/CLS5yrVJ/up.png)](https://postimg.cc/NLCBm4Fr)

After downgrade: [![down.png](https://i.postimg.cc/P5MwNLvy/down.png)](https://postimg.cc/w17vGjVR)

**Comment by dottorblaster** [comment] 2023-07-14 18:21
Same, I can confirm the same behavior as @jcnafi 

![image](https://github.com/Alexays/Waybar/assets/20770/2c7239f9-75ca-4cfc-89b9-81131317271c)

**Comment by Kagukara** [comment] 2023-07-29 23:35
v0.9.18 doesn't load anymore and says `waybar: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory`. Seems to be because `fmt` was updated.

Updating to `Waybar v0.9.20` and also trying `Waybar v0.9.20-48-g20b091dc (branch 'master')`, this issue is still present. Will this be getting fixed anytime soon?

**Comment by tyrumus** [comment] 2023-07-29 23:44
@Kagukara #2223 technically solves this issue, but it requires you to update your config to restore the previous functionality that you were probably expecting. Simply add an array of the workspace names that you want to continue showing the name/icon despite being the focused workspace.

[Here's an example](https://github.com/tyrumus/dotfiles/blob/cfada3de4d7e129f9bf427bd783243fb1373d301/dot_config/waybar/config.tmpl#L25). This currently only works on master.

**Comment by dotfrag** [comment] 2023-07-30 07:10
@tyrumus where did you find that configuration option? I can't seem to find it in the wiki nor it works for me. I still don't see the workspace icons.

**Comment by Kagukara** [comment] 2023-07-30 09:26
> @Kagukara #2223 technically solves this issue, but it requires you to update your config to restore the previous functionality that you were probably expecting. Simply add an array of the workspace names that you want to continue showing the name/icon despite being the focused workspace.
> 
> [Here's an example](https://github.com/tyrumus/dotfiles/blob/cfada3de4d7e129f9bf427bd783243fb1373d301/dot_config/waybar/config.tmpl#L25). This currently only works on master.

That worked, thank you.

**Comment by a1akris** [comment] 2023-09-05 20:36
Apparently, this issue was fixed by this patch #2336. I've just added [an example to the Wiki](https://github.com/Alexays/Waybar/wiki/Module:-Sway#example-4) that shows how to attain the old behavior.

**Comment by jcnafi** [comment] 2023-09-06 10:38
yeah, it get solved putting ` "high-priority-named": ["1", "2"] ` inside ` "format-icons": `.

**Comment by dottorblaster** [comment] 2023-09-06 10:51
Same.

**Closed** 2024-02-19 04:40 UTC
Labels: bug, regression
