### ISSUE TITLE
Hyprland with multi-monitor has wierd click behaviour

### ISSUE THREAD

**Issue by RononDex** [Alexays/Waybar#2164] opened 2023-05-09 06:44 UTC
When running Hyprland with waybar on a multi-monitor setup (using latest waybar-git version) I am experiencing wierd behaviour:

Whenever I click (with the mouse) on a workspace that is on my second screen (where waybar is not rendered) the mouse moves to the second screen and the workspace gets displayed, so far so good.

However, every further click on the waybar will now always trigger this workspace button, it doesn't matter on which module I click. Click on audio module to mute? mouse jumps to second screen and opens the old workspace again. Click on a different workspace button? Mouse moves to second monitor again (no matter which workspace is clicked on) and the old workspace from the first click is shown again.

It even happens when you click on the bar where there are no buttons / modules

It is like that whenever you click on a worskpace  button that is not on the main screen, waybar breaks and the hitbox of that button now overlaps the whole bar.

**Comment by aruhier** [comment] 2023-05-14 11:48
I think it's a duplicate of #1850

**Closed** 2023-06-19 09:56 UTC
