### ISSUE TITLE
commit f41458e with cava module make waybar segfault

### ISSUE THREAD

**Issue by pbosab** [Alexays/Waybar#3185] opened 2024-04-29 18:32 UTC
```
❯ waybar -v
Waybar v0.10.2-11-gf41458ea (branch 'master')

❯ hyprctl version
Hyprland, built from branch main at commit f2b03e9679bc1a091fecffd98b50a4179b5c7d43  (ext-idle-notify: move to new impl).
Date: Mon Apr 29 18:50:07 2024
Tag: v0.39.1-104-gf2b03e96, commits: 4564

flags: (if any)
```

i always had the cava module active, even with the commit 2481f7a and all worked.
since f41458e waybar segfault:
```

apr 29 20:25:35 xxx kernel: waybar[20825]: segfault at ffffffffeb1b877c ip 0000786ea317801d sp 00007ffeeb1b3ac8 error 5 in libc.so.6[786ea3042000+15b000] likely on CPU 2 (core 2, socket 0)
apr 29 20:25:35 xxx kernel: Code: 00 00 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 89 f8 48 89 fa c5 f9 ef c0 25 ff 0f 00 00 3d e0 0f 00 00 0f 87 33 01 00 00 <c5> fd 74 0f c5 fd d7 c1 85 c0 74 57 f3 0f bc c0 c5 f8 77 c3 66
```

and 
```

[2024-04-29 20:25:35.029] [info] Using configuration file /home/xxx/.config/waybar/config
[2024-04-29 20:25:35.030] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[2024-04-29 20:25:35.030] [info] Using CSS file /home/xxx/.config/waybar/style.css
[2024-04-29 20:25:35.036] [info] Hyprland IPC starting
[2024-04-29 20:25:35.038] [info] Loading persistent workspaces from Hyprland workspace rules
zsh: segmentation fault  waybar

```

disabling the cava module make everything works as usual.

**Comment by maxawake** [comment] 2024-05-06 14:00
I have the same problem

**Comment by LukashonakV** [comment] 2024-05-10 13:20
Can you build a debug version of Waybar and try to reproduce it again, Also include the trace logs by running with ```-l trace```

**Comment by hydroxycarbamide** [comment] 2024-05-10 21:26
Hi @LukashonakV, I also had a similar problem but I am no longer able to reproduce it.
The segfault happened with any window manager (swaywm, riverwm and hyprland).

When I wanted to give you some tracelogs today, I had already uninstalled Waybar and only ran the Archlinux binary version (without cava). In order to reinstall Waybar with cava, I tried to recompile libcava (or Waybar with cava subproject) but this failed due to a [problem that has been fixed in cava upstream](https://github.com/karlstav/cava/commit/e23ebaf0a9d87cdfe0fe57c40722a66411a18a21).  I was then able to compile it by updating the libcava subproject in Waybar using the same method as you (simply merging the upstream).

And after successful compilation, I tested Waybar and the problem did not reappear.

(I also tested it by cherry-picking that upstream commit, which also worked without the segfault appearing)

**Comment by pbosab** [comment] 2024-05-11 18:13
> Hi @LukashonakV, I also had a similar problem but I am no longer able to reproduce it. The segfault happened with any window manager (swaywm, riverwm and hyprland).
> 
> When I wanted to give you some tracelogs today, I had already uninstalled Waybar and only ran the Archlinux binary version (without cava). In order to reinstall Waybar with cava, I tried to recompile libcava (or Waybar with cava subproject) but this failed due to a [problem that has been fixed in cava upstream](https://github.com/karlstav/cava/commit/e23ebaf0a9d87cdfe0fe57c40722a66411a18a21). I was then able to compile it by updating the libcava subproject in Waybar using the same method as you (simply merging the upstream).
> 
> And after successful compilation, I tested Waybar and the problem did not reappear.
> 
> (I also tested it by cherry-picking that upstream commit, which also worked without the segfault appearing)

just did the same thing today and solved it.

**Comment by LukashonakV** [comment] 2024-05-11 19:04
Hi @pbosab if it's no more actual,  please close  the issue.  Thanks

**Closed** 2024-05-11 19:05 UTC
Labels: bug, custom, inhibitor, cava
