### ISSUE TITLE
:hover is not working, only on #workspaces?

### ISSUE THREAD

**Issue by AndreasBackx** [Alexays/Waybar#282] opened 2019-04-22 20:03 UTC
Is it true that adding a hover effect in CSS only works for the sway module for the id `workspaces`? I can only get it to work for that. I wanted to enable a hover effect when hovering over modules so I know that it is the right one I'm clicking.

Regarding this same problem, the way to have different colors for icons also would not work here because the CSS in GTK probably doesn't override the HTML defined in the modules. #50 

```javascript
"format": "<span color=\"#fff\">{}</span>"
```

The span element's color would not be able to change on hover or any way at all in CSS. Defining a span inside of the module without a color attribute and trying to change the color of that span inside of there also doesn't work it seems.

**Comment by AdrienLemaire** [comment] 2020-01-30 04:48
I'm also interested in toggling bg/fg on hover. Took me a while to realize that it only works on #workspaces ^^

**Comment by soulfilleddirt** [comment] 2020-02-13 02:25
why is this ?

**Comment by lorendias** [comment] 2020-04-27 20:38
I could specifically use :hover on #custom-xxx:hover elements

Also, :first-child and :last-child would help in instances where buttons are grouped together and the first and last in the group need some kind of curved border-radius or other visual  difference.

**Comment by Kommynct** [comment] 2020-05-26 01:37
Yeah, this seems obvious when we have css... why would this not work?

**Comment by Alexays** [comment] 2020-05-27 07:21
On GTK side, hover seem to work only on button and as workspaces use gtk buttons..

**Comment by Kommynct** [comment] 2020-05-27 11:31
Perhaps everything should or at least being considered a button could maybe be toggleable? I certainly click on my other modules, and I find that hincing something is clickable with a hover effect helps ease of use.

**Comment by Hermitter** [comment] 2020-08-19 03:22
Would love to have this as a feature. Being able to apply hover CSS to modules would let me visually differentiate between which ones have clickable actions.

**Comment by mizzunet** [comment] 2021-12-07 06:13
Any update on this?
```
#clock:hover {
     backround:#232332;
}
``

**Comment by Zaedus** [comment] 2022-06-04 19:22
For those of y'all who are want those cool animations for hovering, I found a pretty good way to do it. Hover effects seem to be exclusive to `GtkButton`s. I checked out PR #1120 because it forced elements with an `on-click` event to be `GtkButton`s. From there I could do whatever `:hover` stuff I wanted.

https://user-images.githubusercontent.com/42098470/172022640-74673166-2609-4776-af24-3b99dc3087c2.mp4

**Comment by rnestler** [comment] 2022-11-09 14:37
Since I had unexpected hover effects everywhere where I have an `on-click` definition after upgrading to 0.9.15 I guess this is now fixed :slightly_smiling_face:

**Closed** 2022-11-15 07:31 UTC
Labels: question

**Comment by zerkalica** [comment] 2023-01-11 14:46
It's possible to rewrite all modules from ALabel to Button?

https://github.com/Alexays/Waybar/blob/master/src/modules/custom.cpp#L7

**Comment by spikespaz** [comment] 2023-01-16 03:16
@zerkalica Is this why I'm having problems?

From what I read, anything with an `on-click` handler is supposed to be a `gtkmm__GtkButton`, however, the `#bluetooth` widget s not a button but rather an `GtkEventBox` containing a `GtkLabel`. This makes it impossible to use `#bluetooth:hover` as a valid selector.

**Comment by izelnakri** [comment] 2023-10-15 12:35
@Alexays This seems like a major drawback of Waybar that has not been addressed, in addition this issue seems to be closed, could you reopen this issue? 


`window#waybar` should have an `:hover` state or at least `.horizontal:hover`. It shouldn't be only buttons as it is very confusing and undocumented mismatch.

**Comment by loegaire** [comment] 2023-10-18 06:45
and :hover on on-click elements stop working again...

**Comment by notmugi** [comment] 2023-10-26 05:10
why is this issue closed? this is a really fundamental part of css thats straight up being ignored. i cant even get custom on-click functions to hover anymore. whats up with that? feels like an oversight that the only things hoverable are workspaces.

**Comment by spikespaz** [comment] 2023-10-26 05:50
Not sure if you guys have looked into the source, but there's no QC...

**Comment by zlietapki** [comment] 2023-12-12 11:46
#custom-XXX:hover still not work. Even with on-click exists  

"custom/apps": {
        "format": "Apps",
        "on-click": "pkill -x rofi || rofi -show drun"
},

#custom-apps:hover {
    color: red;
}

**Comment by phrogg** [comment] 2024-01-03 10:59
I also would love to have this!

**Comment by v4u6h4n** [comment] 2024-01-07 07:15
Damn this isn't a thing yet.

**Comment by samisul** [comment] 2024-03-01 23:35
it doesnt seem to be possible unfortunately

**Comment by EaGLexEyE** [comment] 2024-03-05 14:01
And the issue is still closed.

**Comment by rnestler** [comment] 2024-03-05 15:17
Well it worked at some point, but then got removed again since it caused issues. Maybe it would be worth to create a new feature request for it?

**Comment by 5p4r74cu5** [comment] 2024-03-06 01:12
Done: #2989.
