### ISSUE TITLE
Battery has no discharging status

### ISSUE THREAD

**Issue by g33kex** [Alexays/Waybar#1031] opened 2021-02-11 15:03 UTC
On my system (Slimbook pro X 15), `/sys/class/power_supply/BAT0/status` has 3 possible states: 
* Discharging : power adapter is not plugged in
* Charging : power adapter is plugged in and battery is not full
* Full : power adapter is plugged in and battery is full 

In waybar (version v0.9.5-92-g08e1960), `format-discharging` is never active, and `format-full` is active when battery is at 100% even if the state in  `/sys/class/power_supply/BAT0/status` says "Discharging". I think this might be a bug, since the documentation states that the `status` should correspond to the one in  `/sys/class/power_supply/BAT0/status`. The corresponding CSS styles are not triggered as well.

**Comment by Alexays** [comment] 2021-04-23 10:09
Can you try with latest version?

**Comment by gabegorelick** [comment] 2021-04-26 01:38
> format-full is active when battery is at 100% even if the state in /sys/class/power_supply/BAT0/status says "Discharging"

I can confirm this on `master`. I think it's a regression caused by https://github.com/Alexays/Waybar/pull/923. Specifically, this part of that PR:

> Whenever the capacity has been calculated as 100% show the state as full, so that the formatting rules are applied accordingly

This means that Discharging at 100% gets converted to Full status. You have to wait until capacity hits 99% before it counts as non-full. https://github.com/Alexays/Waybar/blob/5f7329f5b90ffadf3802d0f1f2a7dceb0ba493ab/src/modules/battery.cpp#L219-L223

While some people may want the battery to be marked as "full" if it's at 100%, no matter whether it's charging or not, I think the intention of this code was to only mark as full if it's _charging_ at 100%. Returning "full" when *discharging* seems unintentional according to that comment.

**Closed** 2021-04-26 07:28 UTC
Labels: question
