### ISSUE TITLE
bar height less than 30px

### ISSUE THREAD

**Issue by eoli3n** [Alexays/Waybar#515] opened 2019-12-12 23:14 UTC
Hi

https://github.com/eoli3n/dotfiles/tree/wayland/roles/sway/files/waybar

I tried to set font size to 5, to see if padding does that heavy bar, but it still is 30px.
![img](https://x0.at/WE9.png)

```
~/.config/waybar
❯ grep -ri height

```
Is there any way to have a bar flatter than 30px ?

Adding
```
{
    "layer": "bottom",
    "position": "top",
    "height": 10,
...
```
Results in this weird thing. Size of the area is reduced, but not the bar itself. Window area overrides bar.

![img2](https://x0.at/Ul-.png)

**Comment by Exemplive** [comment] 2019-12-13 08:47
This issue appears to be due to the GTK+3 theme that's applied to Waybar, which is setting that minimum height. See #185 for more on that (as well as a workaround).

**Comment by Alexays** [comment] 2019-12-28 11:06
Yeah as @Exemplive said it's a duplicate of #185

**Closed by Alexays** 2019-12-28 11:06 UTC
