### ISSUE TITLE
Leading/trailing characters on workspace names

### ISSUE THREAD

**Issue by ranisalt** [Alexays/Waybar#407] opened 2019-07-07 23:46 UTC
I'm having weird characters appearing before and after sway workspace names:

![image](https://user-images.githubusercontent.com/1993083/60775334-e76a3200-a121-11e9-9bfe-08b49d3f7e31.png)

This config was copied from another system where it works properly, without these trash. The same fonts are available, and the [same sway config](https://gitlab.com/ranisalt/dotfiles) is being used.

**Comment by Alexays** [comment] 2019-07-08 11:53
Probably duplicate of #115

**Closed by Alexays** 2019-07-08 11:53 UTC
