### ISSUE TITLE
Clock module ignoring timezone

### ISSUE THREAD

**Issue by i-lost-my-bagel** [Alexays/Waybar#3052] opened 2024-03-20 21:37 UTC
After updating waybar to 0.10.0 the clock module is now always giving me UTC regardless of timezone settings.

![image](https://github.com/Alexays/Waybar/assets/32345477/f2b46a08-51cb-4904-ae6a-1f527712cd85)

**Comment by jmayola** [comment] 2024-03-21 04:48
does your waybar/config have a "timezone" option in "clock#time"?
I have the same issue today and i fixed by adding it byside my timezone.
![2024-03-21-014321_hyprshot](https://github.com/Alexays/Waybar/assets/133812832/021c3519-be3d-452d-baae-af732bb02c95)

**Comment by Kommynct** [comment] 2024-03-22 22:36
duplicate of https://github.com/Alexays/Waybar/issues/3024

**Closed** 2024-03-23 08:55 UTC
Labels: custom, clock, inhibitor
