### ISSUE TITLE
network module bandwidth not working

### ISSUE THREAD

**Issue by tlinford** [Alexays/Waybar#1389] opened 2022-01-12 11:24 UTC
With waybar 0.9.9,  `bandwidthDownBits` and `bandwidthUpBits` are always reporting 0b/s, downgrading to 0.9.8 fixes the issue.
Output does not contain any warnings or errors related to network module.

**Comment by bd-g** [comment] 2022-01-13 19:47
This is a duplicate of https://github.com/Alexays/Waybar/issues/1327

**Closed** 2022-01-13 20:08 UTC
