### ISSUE TITLE
[Question] Why does Waybar need Xwayland?

### ISSUE THREAD

**Issue by Yardanico** [Alexays/Waybar#617] opened 2020-03-08 20:20 UTC
Hello! Thanks for your project, I really like it. I've recently set up sway with waybar, everything is working fine, but I noticed a strange thing - for some reason when I kill Xwayland Waybar closes too. Even when I'm running just sway with waybar (with nothing opened), Xwayland is already there. So I was wondering what can be the reason for Waybar to require XWayland?

I'm currently running on Void Linux

**Comment by BoostCookie** [comment] 2020-03-12 07:52
When I `killall Xwayland` Waybar doesn't close. How do you start it in the config of Sway? I use the following:
```
bar {
    position top
    swaybar_command waybar
}
```

**Comment by ericonr** [comment] 2020-03-12 17:30
I've had this same issue on Void. I'm tentatively attributing it to GTK issues. Do you use Firefox as well? Killing XWayland with Firefox open should close it as well.

**Comment by BoostCookie** [comment] 2020-03-12 17:40
> Do you use Firefox as well? Killing XWayland with Firefox open should close it as well.
To use Firefox in Wayland mode you need to set the environment variable MOZ_ENABLE_WAYLAND to 1. ([source](https://wiki.archlinux.org/index.php/Firefox#Wayland))

**Comment by Yardanico** [comment] 2020-03-12 17:41
> When I `killall Xwayland` Waybar doesn't close. How do you start it in the config of Sway? I use the following:
> 
> ```
> bar {
>     position top
>     swaybar_command waybar
> }
> ```

Yes, I use the same.

@ericonr no, I don't use Firefox, maybe it's an issue with GTK on Void? But really seems strange

**Comment by BoostCookie** [comment] 2020-03-13 16:37
> Yes, I use the same.

And how do you start Sway? I use SDDM.

**Comment by Yardanico** [comment] 2020-03-13 17:33
@BoostCookie I start it from the TTY (in bash)

**Comment by ericonr** [comment] 2020-03-14 08:27
> @ericonr no, I don't use Firefox, maybe it's an issue with GTK on Void? But really seems strange

@Yardanico I haven't been able to test it further, but I will as soon as I can. I remember disabling xwayland is Sway settings made stuff change, but I don't remember what exactly.

> To use Firefox in Wayland mode you need to set the environment variable MOZ_ENABLE_WAYLAND to 1. (source)

@BoostCookie  I'm aware! My wofi config takes care of this, currently. That's what made the bug weird, too. Thanks anyway c:

**Comment by accaldwell** [comment] 2020-07-10 02:04
Your issue must be something else - waybar doesnt require Xwayland. It runs just fine with `xwayland disable` in the sway config.

**Comment by ericonr** [comment] 2020-07-10 13:58
Indeed, and it has stopped happening for me as well. I can kill XWayland and Waybar continues working. Might have to do with my updates as well.

**Comment by gspe** [comment] 2021-01-21 20:44
Hi, I've found the reason because this happens.
I'm also using void linux and this behavior depends on how do you launch sway or any other wayland compositor.
The problem is that dbus session is not initialized properly, if you launch sway it tty symply with `sway` dbus session is not initilaized so waybar start with xwayland libreoffice doesn't have the menu bar etc. but if you launch sway with `dbus-run-session sway` or something similar everything works as should be.

So everything depend on how dbus user session is initialized.

**Closed** 2021-04-16 16:14 UTC
Labels: question

**Comment by blackCauldron7** [comment] 2021-08-18 14:06
i have this issue with riverwm
