### ISSUE TITLE
Waybar missing after resume from idle (0.6)

### ISSUE THREAD

**Issue by Oliph** [Alexays/Waybar#290] opened 2019-04-27 13:51 UTC
I still have the waybar missing when I resume from idle. I have the 0.6 version which includes the commit 8cf19826aa3ef3f133cc33cb157baed75fcb838a.
I am happy to provide more debug information (or testing) but fairly new to that process, so if you tell me what you need, I will update this issue.

I also noticed that everytime I resume from idle and the waybar is present, it duplicates the taskbar. At the end I have a lot of duplicated icons. It also duplicated them on my second screen only.

I took a screenshot of it: [https://imgur.com/a/A1dn9YX](https://imgur.com/a/A1dn9YX)

(Thank you for your work!)

Edit: added information about the second screen and a link to a screenshot

**Comment by Alexays** [comment] 2019-04-28 09:37
And if you remove the tray from the config, waybar resume correctly?

**Comment by Oliph** [comment] 2019-04-28 19:02
So far, no issues when the tray is removed.

**Comment by Oliph** [comment] 2019-04-28 21:07
After more tests, the issues is still present even if the tray is removed (removed from the list for the position but not from the config file itself, I don't know if that has an impact)

**Comment by dlasky** [comment] 2019-05-04 00:05
any chance this is resolved now? i was getting similar and i think it was the json thread issue caused by switching workspaces

**Comment by Alexays** [comment] 2019-05-10 11:44
If it was related to the json's problem, it should be fixed, it is?

**Comment by dlasky** [comment] 2019-05-10 11:45
Only mystery commenter knows!! :P

Anything else I can help out on?

**Comment by Alexays** [comment] 2019-05-10 11:51
@dlasky If you have a bt device to debug #169 yeah! ❤️

**Comment by Alexays** [comment] 2019-05-13 13:16
Fixed with 362c393b1d503c708a1c6ae1b1b133c1789e1725
Tested for 20mn with `while true; do swaymsg output eDP-1 disable && sleep 1 && swaymsg output eDP-1 enable; sleep 2; done`

**Closed by Alexays** 2019-05-13 13:16 UTC
Labels: bug
