### ISSUE TITLE
Individual icon size does not work after update 0.9.15

### ISSUE THREAD

**Issue by ruanformigoni** [Alexays/Waybar#1775] opened 2022-11-07 16:29 UTC
Hi,

I was able to change the size for each icon individually with `font-size` in `style.css`, after the update this stopped working.

**Comment by smasher164** [comment] 2022-11-08 04:18
This broke on my system as well. I reverting back to 0.9.13, since my volume icons no longer work.

**Comment by pooh2pooh** [comment] 2022-11-09 20:48
I also have a problem with the size of the text in the panel.

**Comment by vrld** [comment] 2022-11-10 21:46
This seems to be related to #1120, which may have lead to other regressions as well (see #1726, #1753, #1759). I've done some digging and the issue seems to be upstream in the way GTK3 handles button styling. This [answer on stackoverflow](https://stackoverflow.com/a/73967182) gives a workaround:
Instead of
```css
#module {
  font-size: 42px;
}
```
style the label embedded in the button, i.e.:
```css
#module > label {
  font-size: 42px;
}
```

**Comment by steev** [comment] 2022-11-15 05:52
Question about the `#module > label` thing - I personally have 

`* {
        font-size: 14px;
        font-family: monospace;
}`

And font-size isn't elsewhere... in 0.9.13, it said i needed a height of 26 (despite 22 being requested) but now with 0.9.15, it says i need a minimum of 34 and looks like utter trash.  I tried doing

`* > label {
font-size 14px
font-family: monospace
}`

but there were no changes at all.


![This is a screenshot of 0.9.13](https://user-images.githubusercontent.com/7370/201836852-3f941723-82a8-4fab-8a9a-c1fd2d12137e.png)

![This is a screenshot of 0.9.15](https://user-images.githubusercontent.com/7370/201836978-fcea2ccb-ff71-4b6b-b81c-ee425e67ddd8.png)

I am *not* a css master by any stretch of the imagination, but would love to get my setup back to the 0.9.13 looks without having to stay at 0.9.13

**Comment by Alexays** [comment] 2022-11-24 19:30
Closed as reverted

**Closed by Alexays** 2022-11-24 19:30 UTC
Labels: regression
