### ISSUE TITLE
Waybar crashes on startup because of rfkill

### ISSUE THREAD

**Issue by W-joe** [Alexays/Waybar#822] opened 2020-08-14 19:36 UTC
I don't know what rfkill is and I don't want to know.
I went by just fine without it and I'm living a happy life.
However since waybar 0.9.3, more specifically from the change log Network: Added Rfkill status #568 @marcplustwo, waybar refuses to start which makes me sad.

**Comment by W-joe** [comment] 2020-08-14 19:40
P.S. this is my first Issue/Pull request on github, so please bear my mistakes and I'd appreciate it if those were pointed out to me. Thanks.

**Comment by Alexays** [comment] 2020-08-14 19:57
Perfect!

**Comment by theduke** [comment] 2020-09-02 08:10
@Alexays I'm getting the same crash:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Can't open RFKILL control device
```

A compile time config option isn't exactly a great solution...

I disabled the network module for now, which does make it work.

But that's obviously suboptimal.

**Comment by W-joe** [comment] 2020-09-05 08:42
@theduke not wanting to pay for what you don't use isn't odd at all. Just think any custom Linux kernel that doesn't include unwanted/unneeded functionality.
Or source based Linux distributions where you can just disable unneeded features via use flags or some such.

So from my point of view this 'rfkill optional' works as advertised and, at least for me, perfectly fine.

If you come from a binary distribution's point of view one could argue it's incomplete and, indeed, it does still crash for the very same reasons as before.
But the problem is with the incomplete implementation of #568 by @marcplustwo who doesn't check whether or not rfkill is available prior to using it.

Anyways if you need a quick fix maybe make the author of the feature aware of the issue as he is much more familiar with #568 and the problem domain or look into it yourself and make a pull request because I won't be able to allocate a time slot for this any time soon.

**Comment by mcepl** [comment] 2021-03-14 17:08
I guess a duplicate of this bug is https://bugzilla.suse.com/show_bug.cgi?id=1183499 (with the backtrace attached).

**Comment by mcepl** [comment] 2021-03-14 22:18
And it is probably a duplicate of #994.

**Closed** 2021-04-16 16:20 UTC
Labels: bug
