### ISSUE TITLE
Erroneous comma in clock date

### ISSUE THREAD

**Issue by PandorasFox** [Alexays/Waybar#604] opened 2020-02-25 22:38 UTC
Version info:

```
waybar --version
Waybar v0.9.1-12-g2d8dc83 (Feb 20 2020, branch 'master')
```

Example `date` execution:
```
LOCALE=en_US.UTF-8 date +%Y\ %F                                                                                                                 
2020 2020-02-25
```

`clock` config block in my waybar config:
```
	"clock": {
		"locale": "en_US.UTF-8",
		"tooltip-format": "{:%H:%M}\n<tt><small>{calendar}</small></tt>",
		"format-alt": "{:%F}",
		"format": "{:%A | %H:%M}"
	},
```

How this actually renders:

![image](https://user-images.githubusercontent.com/3235827/75293922-141ba880-57dc-11ea-8fdc-c2a484cf75f0.png)

Not gonna lie, I'm confused as hell as to how this happens, since I took a look at clock.cpp and nothing really stands out as a reason for why this happens.

My fix right now is to just replace `%F` with `20%y-%m-%d`, but I'll try to figure out the actual underlying cause and hopefully I'll whip up a pull that fixes this, if it's a waybar issue and not something funky on my system.

**Comment by PandorasFox** [comment] 2020-02-25 23:41
Alright, it appears to be something with how fmt decides to comma-separate numbers depending on the locale - setting `locale` to C for the clock module is a viable workaround.

I'm not sure if this is a problem with how fmt is called from waybar, or if it's an upstream bug in fmt, since I'm not really familiar with fmt at all.

**Comment by alebastr** [comment] 2020-02-25 23:53
Duplicate of #565. 
This is a bug in `date` library. Already fixed in master, but subprojects/date.wrap is pulling older version.

**Closed** 2020-02-26 05:46 UTC

**Comment by PandorasFox** [comment] 2020-02-26 05:48
Ahh, thanks. I'd looked for issues that said "comma" and made this after seeing none.
