### ISSUE TITLE
[Error] Installing Waybar with Cava module

### ISSUE THREAD

**Issue by wowblvck** [Alexays/Waybar#2281] opened 2023-07-04 18:19 UTC
Every time I try to install Waybar with Cava module support I get the following error:

<details><summary>Click to show error</summary>
<p>

FAILED: subprojects/cava-0.8.4/libcava.so 
cc  -o subprojects/cava-0.8.4/libcava.so subprojects/cava-0.8.4/libcava.so.p/src_cavacore.c.o subprojects/cava-0.8.4/libcava.so.p/src_common.c.o subprojects/cava-0.8.4/libcava.so.p/src_config.c.o subprojects/cava-0.8.4/libcava.so.p/src_input_common.c.o subprojects/cava-0.8.4/libcava.so.p/src_input_fifo.c.o subprojects/cava-0.8.4/libcava.so.p/src_input_shmem.c.o subprojects/cava-0.8.4/libcava.so.p/src_output_common.c.o subprojects/cava-0.8.4/libcava.so.p/src_output_terminal_noncurses.c.o subprojects/cava-0.8.4/libcava.so.p/src_output_raw.c.o subprojects/cava-0.8.4/libcava.so.p/src_output_noritake.c.o subprojects/cava-0.8.4/libcava.so.p/src_output_terminal_ncurses.c.o subprojects/cava-0.8.4/libcava.so.p/src_input_alsa.c.o subprojects/
cava-0.8.4/libcava.so.p/src_input_portaudio.c.o subprojects/cava-0.8.4/libcava.so.p/src_input_pulse.c.o subprojects/cava-0.8.4/libcava.so.p/src_input_sndio.c.o subprojects/cava-0.8.4/libcava.so.p/src_input_pipewire.c.o subprojects/cava-0.8.4/libcava.so.p/src_output_sdl_cava.c.o subprojects/cava-0.8.4/libcava.so.p/src_output_sdl_glsl.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libcava.so -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -march=native -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -liniparser -lm /usr/lib/libfftw3.so -pthread -lncursesw -lasound -lportaudio /usr/lib/libpulse.so -lpulse-simple -lsndio /usr/lib/libpipewire-0.3.so /usr/lib/libSDL2.so /usr/lib/libGL.so -Wl,--end-group
{standard input}: Assembler messages:
{standard input}:9: Error: file not found: example_files/config
{standard input}:29: Error: file not found: src/output/shaders/bar_spectrum.frag
{standard input}:49: Error: file not found: src/output/shaders/normalized_bars.frag
{standard input}:69: Error: file not found: src/output/shaders/pass_through.vert
make: *** [/tmp/ccc2NpHx.mk:2: /tmp/ccINWSFu.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make exited with return code 2
compilation aborted.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld exited with return code 1
[162/173] Compiling C++ object waybar.p/src_modules_hyprland_workspaces.cpp.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Interrupt...
 -> build error: waybar-hyprland-cava-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
waybar-hyprland-cava-git - exit status 4

</p>
</details> 

I've tried building directly from git, in which case Waybar doesn't find libcava.so (sudo ldconfig doesn't help). I also tried the wayland-git package from the AUR and this error occurs. I have tried other packages from the AUR but nothing changes. Waybar without the Cava module installs and works great.

WM: Hyprland
OS: Arch
Kernel: 6.4.1-1-cachyos-bore-lto

**Comment by LukashonakV** [comment] 2023-07-05 07:46
Hi @wowblvck , can you please attach meson build log here. Thanks.
Actually I did check for under Gentoo and OpenSUSE and don't see any issues so far. 
Today will try do it under Arch

**Comment by wowblvck** [comment] 2023-07-05 07:56
> Hi @wowblvck , can you please attach meson build log here. Thanks. Actually I did check under Gentoo and OpenSUSE and don't see any issues so far. Today will try do it under Arch

Hi @LukashonakV. Of course, I am attaching my log file. However, since I use the system language - Russian, the log file will be partially in Russian. I hope this won't be a problem to spot the bug. If there are any problems, you can let me know.

[meson-log.txt](https://github.com/Alexays/Waybar/files/11955340/meson-log.txt)

**Comment by LukashonakV** [comment] 2023-07-05 08:03
Hi @wowblvck for at first are you able to switch -O3 flag to -O2 during compilation ? If so please check with -O2 flag

**Comment by wowblvck** [comment] 2023-07-05 08:13
> Hi @wowblvck for at first are you able to switch -O3 flag to -O2 during compilation ? If so please check with -O2 flag

I change CFLAGS -O3 to -O2 and now my makepkg.conf look like:

```
#########################################################################
# ARCHITECTURE, COMPILE FLAGS
#########################################################################
#
CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"

#-- Compiler and Linker Flags
#CPPFLAGS=""
CFLAGS="-march=native -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"
RUSTFLAGS="-C opt-level=3 -C target-cpu=native"
#-- Make Flags: change this for DistCC/SMP systems
MAKEFLAGS="-j$(nproc)"
NINJAFLAGS="-j$(nproc)"
#-- Debugging flags
DEBUG_CFLAGS="-g"
DEBUG_CXXFLAGS="$DEBUG_CFLAGS"
#DEBUG_RUSTFLAGS="-C debuginfo=2"
```

Changing the flag from O3 to O2 had no effect. The error remains.

**Comment by LukashonakV** [comment] 2023-07-05 08:47
@wowblvck  please provide build.ninja log

**Comment by wowblvck** [comment] 2023-07-05 08:52
> @wowblvck please provide build.ninja log

I hope it's him.

[build.ninja.zip](https://github.com/Alexays/Waybar/files/11955919/build.ninja.zip)

**Comment by LukashonakV** [comment] 2023-07-05 09:11
@wowblvck 
Can you build libcava separately please? 

1. `cd waybar/subprojects/cava-0.8.4`
2. `meson setup --wipe build`
3. `meson compile -C build`
Please provide all logs here. Thanks

**Comment by wowblvck** [comment] 2023-07-05 09:23
> @wowblvck Can you build libcava separately please?
> 
> 1. `cd waybar/subprojects/cava-0.8.4`
> 2. `meson setup --wipe build`
> 3. `meson compile -C build`
>    Please provide all logs here. Thanks

Yes. Ready!

[meson-log.txt](https://github.com/Alexays/Waybar/files/11956195/meson-log.txt)
[build.ninja.zip](https://github.com/Alexays/Waybar/files/11956200/build.ninja.zip)

**Comment by LukashonakV** [comment] 2023-07-05 09:49
Actually I have to take a pause. I don't see any significant issues so far. One more try, can you try to build waybar but make sure to move it to the path with only English letters. In order to make sure Russian letters don't impact build process . Thanks. 
The only suspicious moment: according providing info linker for some reason is not able to find compiled cava objects.

**Comment by LukashonakV** [comment] 2023-07-05 09:52
At least you can install libcava from the previous build process using: `meson install -C build`. In such case next building waybar process will find a library and won't build cava again.

**Comment by LukashonakV** [comment] 2023-07-05 09:58
And you can turn off provided compilation options one by one to check whether they are root cause. `Build Options: -Dexperimental=true -Dtests=disabled -Dprefix=/usr -Dauto_features=enabled -Dbuildtype=plain`
I would start with prefix option due to it mostly system responsibility to define prefix path.

**Comment by wowblvck** [comment] 2023-07-05 10:21
@LukashonakV ok. Fine. I made a pure build and installation of Waybar without all options. Everything went without problems, but when trying to launch Waybar, I get a mistake:

`Waybar: Error While Loading Shared Libraries: Libcava.so: Cannot Open Shared Object File: No Such File or Directory`

The `sudo ldconfig` command does not help to correct the error.

<details><summary>Install log</summary>
<p>

```
ninja: Entering directory `build'
[0/1] Installing files.
Installing subprojects/cava-0.8.4/libcava.so to /usr/local/lib
Installation failed due to insufficient permissions.
Attempt to use /usr/bin/sudo to gain elevated privileges? [y/n] y
Installing subprojects/cava-0.8.4/libcava.so to /usr/local/lib
Installing waybar to /usr/local/bin
Installing waybar.5 to /usr/local/share/man/man5
Installing waybar-backlight.5 to /usr/local/share/man/man5
Installing waybar-battery.5 to /usr/local/share/man/man5
Installing waybar-clock.5 to /usr/local/share/man/man5
Installing waybar-cpu.5 to /usr/local/share/man/man5
Installing waybar-custom.5 to /usr/local/share/man/man5
Installing waybar-disk.5 to /usr/local/share/man/man5
Installing waybar-gamemode.5 to /usr/local/share/man/man5
Installing waybar-idle-inhibitor.5 to /usr/local/share/man/man5
Installing waybar-image.5 to /usr/local/share/man/man5
Installing waybar-keyboard-state.5 to /usr/local/share/man/man5
Installing waybar-memory.5 to /usr/local/share/man/man5
Installing waybar-mpd.5 to /usr/local/share/man/man5
Installing waybar-mpris.5 to /usr/local/share/man/man5
Installing waybar-network.5 to /usr/local/share/man/man5
Installing waybar-pulseaudio.5 to /usr/local/share/man/man5
Installing waybar-river-mode.5 to /usr/local/share/man/man5
Installing waybar-river-tags.5 to /usr/local/share/man/man5
Installing waybar-river-window.5 to /usr/local/share/man/man5
Installing waybar-river-layout.5 to /usr/local/share/man/man5
Installing waybar-sway-language.5 to /usr/local/share/man/man5
Installing waybar-sway-mode.5 to /usr/local/share/man/man5
Installing waybar-sway-scratchpad.5 to /usr/local/share/man/man5
Installing waybar-sway-window.5 to /usr/local/share/man/man5
Installing waybar-sway-workspaces.5 to /usr/local/share/man/man5
Installing waybar-temperature.5 to /usr/local/share/man/man5
Installing waybar-tray.5 to /usr/local/share/man/man5
Installing waybar-states.5 to /usr/local/share/man/man5
Installing waybar-wlr-taskbar.5 to /usr/local/share/man/man5
Installing waybar-wlr-workspaces.5 to /usr/local/share/man/man5
Installing waybar-bluetooth.5 to /usr/local/share/man/man5
Installing waybar-sndio.5 to /usr/local/share/man/man5
Installing waybar-upower.5 to /usr/local/share/man/man5
Installing waybar-wireplumber.5 to /usr/local/share/man/man5
Installing waybar-dwl-tags.5 to /usr/local/share/man/man5
Installing waybar-inhibitor.5 to /usr/local/share/man/man5
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/cavacore.h to /usr/local/include/cava/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/common.h to /usr/local/include/cava/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/config.h to /usr/local/include/cava/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/debug.h to /usr/local/include/cava/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/util.h to /usr/local/include/cava/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/input/common.h to /usr/local/include/cava/input/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/input/fifo.h to /usr/local/include/cava/input/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/input/shmem.h to /usr/local/include/cava/input/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/input/alsa.h to /usr/local/include/cava/input/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/input/portaudio.h to /usr/local/include/cava/input/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/input/pulse.h to /usr/local/include/cava/input/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/input/sndio.h to /usr/local/include/cava/input/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/input/pipewire.h to /usr/local/include/cava/input/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/output/common.h to /usr/local/include/cava/output/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/output/terminal_noncurses.h to /usr/local/include/cava/output/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/output/raw.h to /usr/local/include/cava/output/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/output/noritake.h to /usr/local/include/cava/output/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/output/terminal_ncurses.h to /usr/local/include/cava/output/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/output/sdl_cava.h to /usr/local/include/cava/output/
Installing /home/wowblvck/Waybar/subprojects/cava-0.8.4/include/cava/output/sdl_glsl.h to /usr/local/include/cava/output/
Installing /home/wowblvck/Waybar/build/waybar.service to /usr/lib/systemd/user
Installing /home/wowblvck/Waybar/build/meson-private/cava.pc to /usr/local/lib/pkgconfig
Installing /home/wowblvck/Waybar/./resources/config to /usr/local/etc/xdg/waybar
Installing /home/wowblvck/Waybar/./resources/style.css to /usr/local/etc/xdg/waybar
```

</p>
</details>

**Comment by LukashonakV** [comment] 2023-07-05 10:35
You should install it with root privileges

**Comment by LukashonakV** [comment] 2023-07-05 10:59
Please `echo $PATH`

**Comment by wowblvck** [comment] 2023-07-05 11:04
> Please `echo $PATH`

`/home/wowblvck/.nvm/versions/node/v18.16.1/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`

I ran with `su` rights, no change.

I manually added the dynamic library path to `ld.so.conf.d/local.conf > /usr/local/lib` and it worked. Cava module starts. However, it is not clear why it cannot be installed with Waybar.

**Comment by LukashonakV** [comment] 2023-07-05 11:20
> > Please `echo $PATH`
> 
> `/home/wowblvck/.nvm/versions/node/v18.16.1/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
> 
> I ran with `su` rights, no change.
> 
> I manually added the dynamic library path to `ld.so.conf.d/local.conf > /usr/local/lib` update `sudo ldconfig` and it worked. Cava module starts. However, it is not clear why it cannot be installed with Waybar.

I'm trying to get Arch VM. Once it's ready I'll try to reproduce it on Arch.

**Comment by LukashonakV** [comment] 2023-07-06 15:59
Hi @wowblvck , finally I installed archlinux on VirtualBox.
`Linux archlinux 6.4.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:40 +0000 x86_64 GNU/Linux`

So... even with all `Build Options: -Dexperimental=true -Dtests=disabled -Dprefix=/usr -Dauto_features=enabled -Dbuildtype=plain` it compiles, installs and works without any issues... So this is the 3-rd release I've checked and don't see any issues. Arch, OpenSuse, Gentoo(my work production machine)

So I suspect @wowblvck  you've got some specific OS configuration. At least `sudo ldconfig` is pointing on this, because of this is standard command which should refresh library cache. So if even ldconfig doesn't help you - it means there's some issues with your OS configuration

Of course I might wrong too,  but for now my conclusion is this.

**Comment by wowblvck** [comment] 2023-07-07 10:27
> Hi @wowblvck , finally I installed archlinux on VirtualBox. `Linux archlinux 6.4.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:40 +0000 x86_64 GNU/Linux`
> 
> So... even with all `Build Options: -Dexperimental=true -Dtests=disabled -Dprefix=/usr -Dauto_features=enabled -Dbuildtype=plain` it compiles, installs and works without any issues... So this is the 3-rd release I've checked and don't see any issues. Arch, OpenSuse, Gentoo(my work production machine)
> 
> So I suspect @wowblvck you've got some specific OS configuration. At least `sudo ldconfig` is pointing on this, because of this is standard command which should refresh library cache. So if even ldconfig doesn't help you - it means there's some issues with your OS configuration
> 
> Of course I might wrong too, but for now my conclusion is this.
> 
> Upd: @wowblvck can you reproduce the same behavior on another machine?

Unfortunately, I can't reproduce the behavior on another machine.

The `sudo ldconfig` command works, but before that I had to add the path to `/usr/local/lib` to config `ld.so.conf.d`.

My computer configuration is pretty much default except for using the cachyos-bore-lto kernel.

I managed to install everything manually and the kava module works, the only question is why the assembly and installation from the AUR repository is not happening. Apparently, this is a single problem only for me, which means that most likely this is due to the configuration of my machine.

**Comment by LukashonakV** [comment] 2023-07-07 11:29
@wowblvck  as far as I see [linux-cachyos](https://github.com/CachyOS/linux-cachyos) this is pre configured Linux kernel where are done some significant optimizations... 
> GCC/CLANG Optimization with automatically found CPU architecture or also selectable CPU architecture.
> Choose between LLVM/LTO & Thin-LTO or GCC
> Choose between 300Hz, 500Hz, 600 Hz ,750Hz and 1000Hz. Defaults to 500Hz for BORE/CFS/EEVDF and 1000Hz for other schedulers.

Actually I have no idea whether they able to impact current build... at least for the test you can add native Arch kernel 6.4.1. and do Arch loading with native kernel, then try again. 
At least my experiment with the arch out of the box doesn't provide me reproduced issue.

**Comment by LukashonakV** [comment] 2023-07-11 00:38
Hi @wowblvck , cava feature was included into Arch CI container.  Please see [Arch Linux logs](https://github.com/Alexays/Waybar/actions/runs/5513450553/jobs/10051607386#step:5:1). cava is built without any issues. I think this issue might be closed.

**Comment by wowblvck** [comment] 2023-07-12 05:47
> Hi @wowblvck , cava feature was included into Arch CI container. Please see [Arch Linux logs](https://github.com/Alexays/Waybar/actions/runs/5513450553/jobs/10051607386#step:5:1). cava is built without any issues. I think this issue might be closed.

Hmm...I installed the Linux 6.4.3 kernel (without any modifications) and tried again to build waybar with the cava module and an error occurs. I have attached the logs. Without the Cava module, it builds without problems. If the problem is in my computer config, then I will close the issue.

[build.ninja.zip](https://github.com/Alexays/Waybar/files/12024183/build.ninja.zip)
[meson-log.txt](https://github.com/Alexays/Waybar/files/12024185/meson-log.txt)

**Comment by LukashonakV** [comment] 2023-07-12 11:07
Hi @wowblvck 
Let's clarify

1. Did you define `Build Options: -Dexperimental=true -Dtests=disabled -Dprefix=/usr -Dauto_features=enabled -Dbuildtype=plain` which is cause of the failures ? 
2. Made you sure to use the same build options like in [Arch CI ](https://github.com/Alexays/Waybar/actions/runs/5513450553/jobs/10051607386#step:4:1) ? 
3. Did you use official Arch ISO image or CachyOS ? At least according git description CachyOS  is a OS.. not a pure modified Linux kernel. Which means it's not a pure Arch. 
4. Can you get OS snapshot from the machine where you've got an issue and provide it like ISO ? 

You should understand me correct. I'm still suspecting you've got an individual issue due to OS . And I've already spent a lot of time , even modified existing Arch CI in order to catch the issue and no luck so far. And I'm not able reproduce this any ISO image I take from official repositories(Ubuntu, Debian, Manjaro, OpenSUSE, Arch, Gentoo)
So it'll be useful from your side also to try to find out which parameter, or what OS util, configuration cause the issue. Try to install any additional OS into VM for example ...

**Comment by 322sirc** [comment] 2023-07-13 01:36
Hi ,
I have a similar problem building git ver 9.19 on my hyprland partition. 
Weird though I build it on my plasma partition and I didn't get any issue.  
I really don't know what cause the problem both systems installed have pure arch

**Comment by LukashonakV** [comment] 2023-07-13 07:50
Hi @322sirc , so

1. You're using arch hyperland
2. You're using exact waybar from the arch hyperland AUR, waybar-hyprland-cava-git

Can you please do next:

1. Build this Waybar with -Dexperimental=false and check result
2. Can you do git clone from the upstream... means original Waybar repository and try to build.
Thanks

**Comment by wowblvck** [comment] 2023-07-13 08:09
> 

1. Yes, I am using the specified build options.
2.  Yes.
3. I'm use clear and fresh Arch Linux with cachyos kernel. As you know, I tried to change the kernel, but the results remain the same.
4. Unfortunately, I have no experience in creating system snapshots.

Now I'm getting the same error as the user @322sirc

**Comment by wowblvck** [comment] 2023-07-13 08:09
Hi @LukashonakV 

> 1. Yes, I am using the specified build options.
> 2. Yes.
> 3. I'm use clear and fresh Arch Linux with cachyos kernel. As you know, I tried to change the kernel, but the results remain the same.
> 4. Unfortunately, I have no experience in creating system snapshots.
> 
> Now I'm getting the same error as the user @322sirc

**Comment by LukashonakV** [comment] 2023-07-13 08:45
@wowblvck , @322sirc thank you for your help. Finally I've reproduced the same issue.

**Comment by 322sirc** [comment] 2023-07-13 11:08
> Can you please do next:
> 
>     1. Build this Waybar with -Dexperimental=false and check result
> 
>     2. Can you do git clone from the upstream... means original Waybar repository and try to build.
>        Thanks

1. I built it with Dexperimental=false => exact the same errors I've got as up above i detailed.
2. The BUILDPKG in the waybar-hyprland-cava-git call for the last commit that you have in waybar github (when i do updpkgsums gets the last commit/rev in the git stream) 
[meson-log.txt](https://github.com/Alexays/Waybar/files/12038633/meson-log.txt)

......

[138/154] Compiling C++ object waybar.p/src_modules_sndio.cpp.o
FAILED: waybar.p/src_modules_sndio.cpp.o 


I built the waybar-hyprland-git ( the package without cava)  without any issue in my Hyprland-Arch partition....
The issue of building comes only on waybar-hyprland-cava-git....!

**Comment by 322sirc** [comment] 2023-07-13 11:30
> Hi @LukashonakV
> 
>     1. Yes, I am using the specified build options.
> 
>     2. Yes.
> 
>     3. I'm use clear and fresh Arch Linux with cachyos kernel. As you know, I tried to change the kernel, but the results remain the same.
> 
>     4. Unfortunately, I have no experience in creating system snapshots.
> 
> 
> Now I'm getting the same error as the user @322sirc

If you want the new pkg built I have it in my repo  repository---- as I said I could have built it on my plasma system  partition

**Comment by LukashonakV** [comment] 2023-07-17 15:42
Hi @wowblvck . @322sirc  so finally I found the issue. And honestly saying it doesn't related to the Waybar. The problem here is meson parameter `buildtype=plain` means 0 level optimization see meson [specification](https://mesonbuild.com/Builtin-options.html#details-for-buildtype). From the source Waybar is released with `buildtype=release`. In the same time for some reason from yay Archlinux repository it's set to `buildtype=plain` which means repository owner responsible for waybar configuration. So you should contact to the repository owner to fix this.

**Comment by wowblvck** [comment] 2023-07-17 15:54
> Hi @wowblvck . @322sirc so finally I found the issue. And honestly saying it doesn't related to the Waybar. The problem here is meson parameter `buildtype=plain` means 0 level optimization see meson [specification](https://mesonbuild.com/Builtin-options.html#details-for-buildtype). From the source Waybar is released with `buildtype=release`. In the same time for some reason from yay Archlinux repository it's set to `buildtype=plain` which means repository owner responsible for waybar configuration. So you should contact to the repository owner to fix this. I have no idea why the repo owner has changed this parameter.

Hi @LukashonakV. I'm try to build from [this](https://aur.archlinux.org/packages/waybar-git) AUR repository with @Alexays is mainainer. I'm replace `buildtype=plain` for `buildtype=release` with enabled Cava module. I still get an error and the build is aborted.

**Comment by LukashonakV** [comment] 2023-07-17 20:11
@wowblvck  uff . I'm still not unable to even reproduce. I've checked exact mentioned repository ... on pure Arch ... and built waybar with cava without any issues. (((
Can you please share `meson configure build > meson_prm.txt`
Can we schedule the session you'll show what's going on on your machine?

**Comment by 322sirc** [comment] 2023-07-17 20:25
As I said I think it is something interfere with active cava modules..
cause on hyprland with cava modules active gets the error of building.
On plasma Arch it builds without issue
I do not use yay to build my pkgs -just makepkg -sc

I will document both live building the pkg on hyprland and on plasma...give
me some time please...I'll be back

**Comment by 322sirc** [comment] 2023-07-17 20:41
Ok so I record all the building in this way: makepkg -s > build.system.txt...where system = hyprland or plasma. Ill attache both txts.  
[build.hyprland.txt](https://github.com/Alexays/Waybar/files/12073735/build.hyprland.txt)
[build.plasma.txt](https://github.com/Alexays/Waybar/files/12073737/build.plasma.txt)

**Comment by LukashonakV** [comment] 2023-07-17 20:53
Thank you @322sirc ... let me check that with new meson.
FYI: I've already tried to check both : with cava installed in the system .. and as a subproject of waybar .

**Comment by 322sirc** [comment] 2023-07-17 20:57
That is ok ...I didn't update the plasma system....iit is not the culprit have the files here ...
[build.hyprland.txt](https://github.com/Alexays/Waybar/files/12073817/build.hyprland.txt)
[build.plasma.txt](https://github.com/Alexays/Waybar/files/12073819/build.plasma.txt)
[build.plasma.mason1.1.1.txt](https://github.com/Alexays/Waybar/files/12073821/build.plasma.mason1.1.1.txt)

**Comment by LukashonakV** [comment] 2023-07-17 21:04
@322sirc  the thing why on plasma Waybar with cava is built successful is: cava is built as a subproject. It is not installed in the system. Where on hyperland cava installed and exists in the system.
FYI: I've checked meson .. not any issue on my machine

**Comment by LukashonakV** [comment] 2023-07-17 21:23
The problem here is: Waybar and cava have got different objects but with the same name. Class name is sndio.  But there is one more base standard library sndio which both waybar and cava objects refer to. 
So when cava is installed next build waybar process include system library headers in order to meet dependency requirements. Here the most tricky moment. For some reason on you machine cava sndio is provided to waybar sndio class instead of standard sndio library. That's why waybar sndio doesn't see sndio API.

**Comment by LukashonakV** [comment] 2023-07-18 12:35
@wowblvck , @322sirc  I'll provide PR soon. It should help.

**Closed** 2023-07-18 14:59 UTC
Labels: bug, help wanted

**Comment by sudg6** [comment] 2026-06-27 15:14
> > Please `echo $PATH`
> 
> `/home/wowblvck/.nvm/versions/node/v18.16.1/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
> 
> I ran with `su` rights, no change.
> 
> I manually added the dynamic library path to `ld.so.conf.d/local.conf > /usr/local/lib` update `sudo ldconfig` and it worked. Cava module starts. However, it is not clear why it cannot be installed with Waybar.

@LukashonakV @Alexays  I was wondering why this issue was closed, as I'm still getting the same error until I manually created `/etc/ld.so.conf.d/local.conf` and included `/usr/local/lib`, which contains `libcava.so`, then, `sudo ldconfig` after all of which made `wayland` finally working!
