### ISSUE TITLE
Network sometimes shows as disconnected when it's not

### ISSUE THREAD

**Issue by pedrocr** [Alexays/Waybar#388] opened 2019-06-15 16:26 UTC
I often get the network shown as Disconnected when it's actually not. Restarting waybar fixes it. Let me know what kind of information you need to debug this.

**Comment by FreeFull** [comment] 2019-06-15 20:42
It seems like https://github.com/Alexays/Waybar/issues/354 came back. I'm also experiencing this.

**Comment by niktob560** [comment] 2019-06-16 12:01
Same problem today came. Shows "disconnected" all time, excepting time wifi-menu is open in terminal  
Arch Linux  
Waybar v0.6.6-28-gfcf2d18 (May 30 2019, branch 'master')

**Comment by apognu** [comment] 2019-07-08 09:45
Experiencing the same issue, but on my end, it seems related to multihead and/or sleep. Whenever I come back from sleep, the status shows disconnected until I reload sway, and sometimes, one of the screen shows my SSID while the other shows up disconnected.

**Comment by pedrocr** [comment] 2019-07-09 13:29
I see this happen a lot when I change Wifi networks. I think I can reproduce this mostly at will.

**Comment by MichaelAquilina** [comment] 2019-07-29 15:50
I came here to post an issue that https://github.com/Alexays/Waybar/issues/354 was back and found this issue. In my case, the network connection is just out of date. For example it would show wireless as active when I would have deactivated it.

**Comment by farid-fari** [comment] 2019-07-31 03:54
Am also affected, though I cannot link directly to sleep

**Comment by pedrocr** [comment] 2019-08-16 17:24
This is really annoying. I wondered today if it was something to do with changing between APs with the same SSID.

**Comment by GrantMoyer** [comment] 2019-10-19 21:24
I can reproduce this reliably:

System Arch Linux, systemd-networkd, iwd.

*/etc/systemd/network/25-wireless.network*:
```
[Match]
Name=wlan0

[Network]
DHCP=yes
```

Steps to reproduce:

1. Connect to network *A*: `iwctl station wlan0 connect A`
2. Connect to network *B*: `iwctl station wlan0 connect B`
3. Restart waybar. At this point, the network B should be shown by the Network module.
4. Connect back to network *A*: `iwctl station wlan0 connect A`. The network module will now show a disconnected state.

The problem can be temporarily resolved by *either*:

* Restarting waybar
* Restarting systemd-networkd: `systemctl restart systemd-networkd.service`

**Comment by Neules** [comment] 2020-04-25 09:18
In my case uncommenting `Interface wlp4s0`line in `config` and letting the ip be static solves the problem. 

Before that change, `ip addr` showed lot of ip6 addresses and 2 ip4 addresses. I changed to static ip and now I have just one ip4 and one ip6. The problem has gone.

I have 2 wireless nets in my house so If I go to the garden it connects to the second net.

**Comment by chron-isch** [comment] 2020-07-03 13:20
I'm having the same problem with Arch, sway and current master, restarting waybar or disabling&enabling the output waybar is using also updates it.

**Comment by varac** [comment] 2020-07-03 13:29
Same here with `Waybar v0.9.2 (Apr 11 2020, branch 'master')` on Ubuntu 20.04 with sway `1.4-f681d529 (Jan 22 2020, branch 'heads/1.4')`

**Comment by GbGp** [comment] 2020-10-17 16:30
I can reproduce this issue with iwd by simply switching to another AP or even by simply disconnecting or reconnecting to the same one.

I'm trying to monitor the events passed to Network::handleEvents, but it looks like I miss many events when I use a debugger compared to just printing nlmsg_type to stdout. I don't now much about libnl so I can't say if that's just some timeout or a race condition somewhere in the code. Also, I can't reproduce a single case where Network::checkNewInterface finds a valid interface.
From what I see I am quite confident that #511 is the same issue as this one.

For now I managed to work around the issue by skipping checkNewInterface and just kicking the timer  https://github.com/GbGp/Waybar/commit/3271258d97c0710e6de9a619cd87dc8f12fd7d15, but I'm not sure what I'm breaking there.

**Comment by dR3b** [comment] 2020-10-20 13:36
Same here with NetworkManager on Arch Linux (Waybar v0.9.4)

**Comment by endorsystems** [comment] 2020-10-22 14:49
Arch Linux kernel 5.9.1-arch1-1 / Waybar v0.9.4 / sway version v1.5

Refreshing sway fixes it.

**Comment by insidewhy** [comment] 2020-12-27 04:53
Same problem here with latest everything:

5.9.14-arch1-1
waybar 0.9.4-5
networkmanager 1.26.4-1

Restarting waybar shows my connection again, but after a few minutes it goes back to showing "disconnected" again.

**Comment by petrmanek** [comment] 2021-01-04 11:00
Hi also experiencing this with the latest version:

 - linux 5.10.4.arch2-1
 - waybar 0.9.5-2
 - networkmanager 1.26.4-1

Same symptoms as described above. Please let me know if I can provide any more data useful for troubleshooting.

**Comment by savchenko** [comment] 2021-01-25 09:21
Can confirm. Given how easy is to jam a script that outputs some basic network information (which can be pulled by `waybar`) and [sheer number of bugs reported about the network module](https://github.com/Alexays/Waybar/issues?q=is%3Aissue+is%3Aopen+network+label%3Abug), I wonder if it is worth investing time in it?

Perhaps shipping some basic `*.sh` and focusing on the core functionality will provide a better ROI?

**Closed** 2021-05-21 15:02 UTC
Labels: bug

**Comment by pedrocr** [comment] 2021-05-21 15:50
This is even worse for me after this merge. After a little while of waybar being running it just changes to "Disconnected".

**Comment by Alexays** [comment] 2021-05-22 08:35
@tperard any idea?

**Comment by tperard** [comment] 2021-05-23 12:54
> This is even worse for me after this merge. After a little while of Waybar being running it just changes to "Disconnected".

Hi @pedrocr, thanks for testing the changes!

Let's try to debug that.
Could you let me know of your configuration for the network module? (At least the value for "`interface`".)
Could you let me know the state of your network interface as reported by `ip link`, for both when Waybar shows it as connected and as "Disconnected".
Could you try to run Waybar with "`--log-level debug`"? (I'm interested in at least the log lines which have "network:" if you want to trim the log.)
It seems your network interface is WiFi, it probably doesn't matter but do you use `iwd` or `wpa_supplicant` for it?

If you only have answer to some of those question, but not all, it still going to be useful.

Cheers.

**Comment by minhduc0711** [comment] 2021-05-24 02:35
@tperard I have the same issue, so just chiming in :)
* Network module config
```
"network": {
    "interface": "wlp3s0",
	...
}
```
* `ip link` outputs the same thing whether Waybar displays "connected" or "disconnected":
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp2s0f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN mode DEFAULT group default qlen 1000
    link/ether 98:29:a6:48:90:5c brd ff:ff:ff:ff:ff:ff
3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DORMANT group default qlen 1000
    link/ether 98:22:ef:77:0a:cd brd ff:ff:ff:ff:ff:ff
```
* Waybar log does not print anything when the bar changes to "disconnected". I only spot these lines when starting waybar:
```
[2021-05-24 09:25:40.911] [debug] network: selecting new interface wlp3s0/3
[2021-05-24 09:25:40.911] [debug] network: wlp3s0, new addr 192.168.100.6/24
```
* I do use `wpa_supplicant`.

**Comment by Alexays** [comment] 2021-05-27 19:25
@minhduc0711 can you test with latest @tperard changes? #1116

**Comment by minhduc0711** [comment] 2021-05-28 01:44
It works well now, thanks for looking into it!!
