### ISSUE TITLE
network module outputs `lo` instead of `wlan0`

### ISSUE THREAD

**Issue by mizzunet** [Alexays/Waybar#1468] opened 2022-03-09 01:39 UTC
![image](https://user-images.githubusercontent.com/10193999/157355290-92136a77-40bc-4071-91d5-15fe2ac44c6a.png)
I have set interface as `wlan0`, but this module outputs just `lo`. The network manager is `iwd`. Earlier, it was working fine, that is, displaying `wlan0`'s `{icon}`

```
        "network": {
	 "interval": 5,
        "format-wifi": "<span size='103%' rise='600'>{icon}</span>",
        "format-icons": ["󰤯", "󰤟", "󰤢", "󰤥", "󰤨"],
        "format-disconnected": "󰤭",
        "interface": "wlan0",
	    "tooltip-format-wifi": "{essid}:{signalStrength}\nSpeed:{bandwidthDownBits} \n{ipaddr}"
    },
```
`ip a`
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 brd 127.255.255.255 scope host lo
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 18:cf:5e:70:ef:86 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.5/24 scope global noprefixroute wlan0
       valid_lft forever preferred_lft forever
```
`waybar`
```
 waybar
[2022-03-09 07:09:49.417] [info] Using configuration file /home/missu/.config/waybar/config
[2022-03-09 07:09:49.417] [info] Using CSS file /home/missu/.config/waybar/style.css
[2022-03-09 07:09:49.437] [warning] As using a timezone, some format args may be missing as the date library haven't got a release since 2018.
[2022-03-09 07:09:49.452] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity

** (waybar:6312): WARNING **: 07:09:49.497: gtk-layer-shell v0.7.0 may not work on GTK v3.24.33. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
[2022-03-09 07:09:50.697] [warning] Requested height: 30 is less than the minimum height: 32 required by the modules
[2022-03-09 07:09:50.697] [info] Bar configured (width: 1366, height: 32) for output: eDP-1
^C⏎
~ 25s
❯ waybar
[2022-03-09 07:10:15.532] [info] Using configuration file /home/missu/.config/waybar/config
[2022-03-09 07:10:15.533] [info] Using CSS file /home/missu/.config/waybar/style.css
[2022-03-09 07:10:15.555] [warning] As using a timezone, some format args may be missing as the date library haven't got a release since 2018.
[2022-03-09 07:10:15.575] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity

** (waybar:6483): WARNING **: 07:10:15.657: gtk-layer-shell v0.7.0 may not work on GTK v3.24.33. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
[2022-03-09 07:10:15.765] [info] Bar configured (width: 1366, height: 32) for output: eDP-1
```

config: https://0x0.st/oPhF.txt
style.css: https://0x0.st/oPhC.css

**Comment by jonasc** [comment] 2022-03-09 21:28
I can confirm similar behavior. For me it always shows my ethernet controller even though I have configured it to show my wifi controller (`"interface": "wl*"`). I'm currently bisecting the source code to see whether I can find the "offending" commit to help debug this.

**Comment by jonasc** [comment] 2022-03-09 22:06
Okay, so sadly my `bisect` journey could only limit the commits down to the following due to many of them either not compiling or dumping core before I was able to see the output:

_There are only 'skip'ped commits left to test.
The first bad commit could be any of:
d22d6a45222ebc1b6b060a1a45f2405d0d47ecfc
2301788a810b64be9361b15fbd8f510002c74cc4
bb7b376fa6edc121890021ed191cdf497a5df66f
667d0a45f46d0b2fc34b300e639b035d7c091345
e10c9dd011e394b734be7bab6fc2ca6885f9de1f
65dd245362fb203942b4a5a968e755a33ed880a6
b0eab5d793e48af1fcfc4b281aab6bfbd10b769b
17bb5643aec1ec67d7a0c45bfc91ad806b842a75
c4cc7ae396b8f040522ec3fcf76b9f9fbd1c65d4
1c08d26af0245e9bc3f35902d8f6b66a41a17764
We cannot bisect more!_

I hope that this still helps. If I have time I might have another look.

**Comment by jonasc** [comment] 2022-03-09 22:37
I identified the culprit as e10c9dd011e394b734be7bab6fc2ca6885f9de1f. Reverting this single commit brings back the configured interface for me. I'm deep enough into the code to understand
1. why this change has the observed effect and
2. why this change was made initially.

I guess it'd be best if @mazunki could give some input on why this change was made and whether it can be reverted without further problems.

**Comment by mazunki** [comment] 2022-03-09 22:40
> I identified the culprit as [e10c9dd](https://github.com/Alexays/Waybar/commit/e10c9dd011e394b734be7bab6fc2ca6885f9de1f). Reverting this single commit brings back the configured interface for me. I'm deep enough into the code to understand
> 
>     1. why this change has the observed effect and
> 
>     2. why this change was made initially.
> 
> 
> I guess it'd be best if @mazunki could give some input on why this change was made and whether it can be reverted without further problems.

https://github.com/Alexays/Waybar/issues/1455#issuecomment-1061447544 references the same issue.

**Comment by jonasc** [comment] 2022-03-09 23:16
Oh, thanks for the pointer. I should have looked further than just the first issue I found here, that would've spared me some time 🤷.

**Comment by mazunki** [comment] 2022-03-09 23:32
> Oh, thanks for the pointer. I should have looked further than just the first issue I found here, that would've spared me some time 🤷.

To be fair, this issue has a better title. I have had the same issue for a while, never realized my change introduced it! I think there's some other effect at play, though, since I didn't experience the problem when I first tried changing it.

**Comment by Alexays** [comment] 2022-03-10 08:54
Should be fixed with latest version/master :)

**Closed by Alexays** 2022-03-10 08:54 UTC

**Comment by spr1t3-0** [comment] 2023-01-04 11:54
I am still experiencing this
