### ISSUE TITLE
I can't Update to version 2023-07-05 01:20 (UTC)

### ISSUE THREAD

**Issue by mrp4sten** [Alexays/Waybar#2419] opened 2023-08-17 17:25 UTC
Im trying to Update this package from <https://aur.archlinux.org/waybar-hyprland-git.git> and I have to many errors. 
Im using Arch Linux 
![1692292910_screenshot](https://github.com/Alexays/Waybar/assets/62355061/7f62ac44-d93f-478a-9ce9-d3054e60d002)

And this is an example from the errors:
![1692293013_screenshot](https://github.com/Alexays/Waybar/assets/62355061/46358307-eabf-44e7-9cd3-8f2155360166)

Can you see the full log here: 
[log-error.log](https://github.com/Alexays/Waybar/files/12372100/log-error.log)

**Comment by zjeffer** [comment] 2023-08-17 17:36
Duplicate of #2415 ?

**Comment by Alexays** [comment] 2023-08-18 07:45
Closing as duplicate

**Closed by Alexays** 2023-08-18 07:45 UTC

**Comment by mrp4sten** [comment] 2023-08-19 06:09
Thanks for the information!!
The solution was uninstall `waybar-hyprland-git`, install `spdlog-git` and reinstall `waybar-hyprland-git`.
:heart: :penguin: 

```shell
paru -Rns waybar-hyprland-git
paru -S spdlog-git
paru -S waybar-hyprland-git
```
