### ISSUE TITLE
wlr/taskbar crashes on icon missing from GTK theme

### ISSUE THREAD

**Issue by nwg-piotr** [Alexays/Waybar#967] opened 2021-01-07 03:47 UTC
The [app in Go](https://github.com/nwg-piotr/nwgocc) I'm working on has just been given a [.desktop file](https://github.com/nwg-piotr/nwgocc/blob/master/nwgocc.desktop) and an icon, located in `/usr/share/nwgocc/nwgocc.svg`. On Wayfire I use Waybar with the wlr/taskbar module.

```
"format": "{icon} {title:.15}",
```
Unless I remove `{icon}`, launching my program crashes Waybar with the message like this:

> [2021-01-07 04:27:51.301] [error] Icon '/usr/share/nwgocc/nwgocc.svg' not present in theme Papirus-Dark

~~My other app, written in python, that stores the icon in `/usr/share/azote/azote.svg` doesn't crash Waybar. I wonder if this is a bug in Waybar, or maybe in my golang code. Could anybody help?~~

**EDIT:** Placing the icon in `usr/share/pixmaps` and using just the `nwgocc` name  in the .desktop file resolves the issue. I'll leave the issue open for a while, in case the Author wanted to know and catch the possible exception.

**Comment by berbiche** [comment] 2021-02-07 00:03
I ran into this same issue.

@nwg-piotr could you please re-open?

I don't expect Waybar to crash if an icon is missing when using `wlr/taskbar`.

Last log line with `--log-level=trace`:
> [2021-02-06 18:58:43.776] [error] Icon 'network.cycles.wdisplays' not present in theme Adwaita

Info: `Waybar v0.9.5-ff9f09a2 (branch 'master')`

**Comment by nwg-piotr** [comment] 2021-02-07 00:10
Sure.

**Comment by Alexays** [comment] 2021-02-08 08:10
@berbiche this should be fixed on master by @jgmdev :)

**Comment by berbiche** [comment] 2021-02-08 22:44
Thanks, I confirm the issue is resolved.

**Closed** 2021-02-08 22:44 UTC
