### ISSUE TITLE
The second of the clock shows 8 decimal points

### ISSUE THREAD

**Issue by kaymio** [Alexays/Waybar#2400] opened 2023-08-13 18:42 UTC
![2023-08-13-204035_grim](https://github.com/Alexays/Waybar/assets/22966929/c60de255-6f4f-48ee-a5eb-8e1f22a97162)

The second works as intended, but it shows now 8 decimal points of a second.

` 
 "clock": {
        "interval": 1,
        "format":"{:%A | %Y-%m-%d | %H:%M  | %Ss}"
    },
`

waybar on Manjaro stable with version 0.9.20-2

**Comment by zjeffer** [comment] 2023-08-13 19:13
This doesn't look like it's caused by Waybar. What's the output of `date "+%S"` when running in a terminal?

**Comment by Cornelicorn** [comment] 2023-08-13 19:47
I'm having the same issue, `date "+%S"` shows only the seconds, e.g. `48`.

**Comment by Cornelicorn** [comment] 2023-08-13 20:04
Using `%X` to use the time format from my locale does not show the seconds decimal points.

**Comment by zjeffer** [comment] 2023-08-13 20:32
What is the output of `cat /etc/locale.conf`?

**Comment by cryptsight** [comment] 2023-08-13 20:45
Hi, I'm having the same issue since I switch to Arch a few days ago.

LANG=en_US.UTF-8

**Comment by cryptsight** [comment] 2023-08-13 21:07
@Cornelicorn using the clock module with format :%X is working for me.

**Comment by zjeffer** [comment] 2023-08-13 21:21
Strange, I'm also on Arch with the same locale and if I try the same config for the clock module it just shows me the seconds, without the decimal points. Using the latest master.

**Comment by Cornelicorn** [comment] 2023-08-13 22:04
> What is the output of `cat /etc/locale.conf`?

```
$  cat /etc/locale.conf
LANG=en_US.UTF-8
LC_TIME=de_DE.UTF-8
```

But this was independent of the specific locale for me,
`%S` shows seconds with decimal points, `%X` without the decimal points.
I'll try compiling waybar from master tomorrow.

**Comment by kaymio** [comment] 2023-08-14 04:55
Also 

`LANG=de_DE.UTF-8  LC_TIME=de_DE.UTF-8`

are Germans overly precise again?

**Comment by zjeffer** [comment] 2023-08-14 09:07
I tried running waybar with @kaymio's LANG and LC_TIME envvars and config, but I get this:

```
>  LANG=de_DE.UTF-8 LC_TIME=de_DE.UTF-8 waybar --config config.jsonc

(process:250218): Gtk-WARNING **: 11:01:16.025: Locale not supported by C library.
        Using the fallback 'C' locale.
[2023-08-14 11:01:16.074] [info] Using configuration file config.jsonc
[2023-08-14 11:01:16.074] [info] Using CSS file /etc/xdg/waybar/style.css
[2023-08-14 11:01:16.085] [warning] module clock: Disabling module "clock", locale::facet::_S_create_c_locale name not valid
[2023-08-14 11:01:16.086] [info] Bar configured (width: 1920, height: 32) for output: HDMI-A-1
```

---

> The output is a second, without decimals.

So your waybar is giving different results than the output of `date`? 

What happens if you add this module:

```jsonc
"custom/text": {
    "interval": 1,
    "format": "{}",
    "exec": "date '+%S'"
},
```

**Comment by natpuch** [comment] 2023-08-14 09:15
I have the same problem on 0.9.20 with `LANG=en_GB.UTF-8` locale but I think this was fixed in #2345, right?

**Comment by Cornelicorn** [comment] 2023-08-14 09:16
A git-bissect shows that this issue has been resolved with https://github.com/Alexays/Waybar/commit/dae7794bdfda81460beb26ad90a3beec2ab18bf2 on master.
I reported the bug in Arch: https://bugs.archlinux.org/task/79371.

**Comment by zjeffer** [comment] 2023-08-14 09:22
Ah, if it's fixed in the master than that's fine. You shouldn't really have to create an Arch bug report for this, the waybar package should just be updated once a new waybar release drops. This issue can be closed as it's a duplicate of #2344 @kaymio.

@Alexays Any ETA on the next release?

**Comment by Cornelicorn** [comment] 2023-08-14 09:25
> Ah, if it's fixed in the master than that's fine. You shouldn't really have to create an Arch bug report for this, the waybar package should just be updated once a new waybar release drops.

Arch added a master patch for e9b29613, which makes the release compilable on arch at all, but also introduces this format error, so I think it's reasonable they also add the patch to fix this, of course if the next release is a few days in the future, that might be unnecessary.

**Comment by zjeffer** [comment] 2023-08-14 09:31
Ah, I see, in that case it makes sense to patch it.

**Comment by Alexays** [comment] 2023-08-14 13:32
Will release a new version today!

**Closed** 2023-08-14 13:35 UTC
