### ISSUE TITLE
The language module doesn't always fit

### ISSUE THREAD

**Issue by baltitenger** [Alexays/Waybar#1743] opened 2022-10-20 17:27 UTC
Its contents just get replaced with `...`.

![image](https://user-images.githubusercontent.com/21960678/197017444-a3a8efb8-e261-4c84-a6b0-a0e004d9943b.png)
![image](https://user-images.githubusercontent.com/21960678/197017486-821cb553-df98-480a-8044-37f0a867154d.png)

I'm guessing it's due to some recent commit making every button's `min-size` hardcoded 0.

Reproducible on the default config as well. I'm not sure why only the language button exhibits the issue, but everything else works fine.

**Comment by pinselimo** [comment] 2022-10-21 09:53
> I'm not sure why only the language button exhibits the issue, but everything else works fine.

That's because the ``language`` button is initialized with ``ellipsize = true``. The ``mode`` button is the only other one to do so as well. Seems inconsistent indeed.
The default ``min-size`` property of buttons was just enough to fit two characters. So the issue existed already but has now become more apparent.

**Comment by grfrederic** [comment] 2022-11-03 09:01
hi, i'm experiencing the same problem. is there a way to fix it temporarily using `style.css`? in my case the `min-width` parameter is ignored, is that normal?

**Comment by pinselimo** [comment] 2022-11-03 10:51
@Alexays could a solution be to make the ``ellipsize`` parameter adjustable for the user?

**Comment by grfrederic** [comment] 2022-11-13 09:32
why would that be preferable to initializing it with `ellipsize = false`, is there a reason someone would want this particular module (and I guess `mode`) to ellipsize and others not? also, could you point me to where this default initialisation happens? I can't find it.

**Comment by anarcat** [comment] 2022-11-21 20:43
this seems to be a duplicate of #952

**Comment by tigerjack** [comment] 2022-11-23 08:46
@Alexays I don't think this is due to the recent 0.9.15 regression. The problem with the language module has been around for ages for me. I was just too lazy to open a bug report.

**Comment by pinselimo** [comment] 2022-11-23 16:20
> @pinselimo why would that be preferable to initializing it with `ellipsize = false`, is there a reason someone would want this particular module (and I guess `mode`) to ellipsize and others not?

I don't know, but I assume there is a reason for this default to be different to begin with. I would be absolutely fine with just changing it.

> also, could you point me to where this default initialisation happens? I can't find it.

Ofc, here you go: https://github.com/Alexays/Waybar/blob/master/src/modules/sway/language.cpp#L21

**Comment by Alexays** [comment] 2022-11-24 19:30
Closed as reverted

**Closed by Alexays** 2022-11-24 19:30 UTC
Labels: regression
