### ISSUE TITLE
Custom module with interval is disappearing

### ISSUE THREAD

**Issue by vyachkonovalov** [Alexays/Waybar#818] opened 2020-08-12 16:16 UTC
https://files.landofooo.fun/f/recording.mp4

When I click on test2, test1 disappear within new interval tick.

**waybar.conf**
```json
{
    "layer": "top",
    "modules-right": [
        "custom/test1",
        "custom/test2"
    ],
    "custom/test1": {
        "exec": "date +%s",
        "interval": 1
    },
    "custom/test2": {
        "exec": "/home/slava/code/scripts/test.sh",
        "on-click": "touch /home/slava/code/scripts/test.sh"
    }
}
```
**test.sh** (or any other module that changes output with a click on it, not only custom)
```shell
#!/usr/bin/env bash

while true
do
  echo --- ${RANDOM:0:3} ---
  inotifywait -qq -e close $HOME/code/scripts/test.sh
done
```

log
```log
[2020-08-12 21:05:21.819] [info] Resources files: waybar.conf, /home/slava/.config/waybar/style.css
[2020-08-12 21:05:21.824] [debug] Output detected: HDMI-A-2 (Philips Consumer Electronics Company PHL 245E1)
[2020-08-12 21:05:21.831] [debug] Cmd exited with code 0
[2020-08-12 21:05:21.890] [debug] Set surface size 2560x26 for output HDMI-A-2
[2020-08-12 21:05:21.890] [debug] Set exclusive zone 26 for output HDMI-A-2
[2020-08-12 21:05:22.850] [debug] Cmd exited with code 0
[2020-08-12 21:05:23.869] [debug] Cmd exited with code 0
```

errors
```
** (waybar:210060): WARNING **: 21:05:21.875: gtk-layer-shell was not compiled with support for GTK v3.24.22, program may crash

** (waybar:210060): WARNING **: 21:05:21.875: gtk-layer-shell was not compiled with support for GTK v3.24.22, program may crash

(waybar:210060): Gdk-WARNING **: 21:05:25.338: Couldn't map window 0x55dd26412d10 as subsurface because its parent is not mapped.

** (waybar:210060): WARNING **: 21:05:25.338: gtk-layer-shell was not compiled with support for GTK v3.24.22, program may crash
```

I've also tried this config with empty style.css and longer interval for the test1 module.

Waybar v0.9.3
sway version v1.5
ArchLinux 5.7.12-arch1-1

**Comment by jplatte** [comment] 2020-08-13 15:50
Duplicate of #815?

**Comment by Alexays** [comment] 2020-08-14 19:58
Yep, dups of #815

**Closed by Alexays** 2020-08-14 19:58 UTC
