### ISSUE TITLE
Height of bar changes with logo size

### ISSUE THREAD

**Issue by bernharl** [Alexays/Waybar#1458] opened 2022-03-07 08:50 UTC
After the latest version added support for application logos, it sporadically changes height based on the application in focus (using Sway). 

Steps to reproduce:
1. Focus an application with a small logo, for example foot terminal
2. Switch focus over to an application with a larger logo, for example pavucontrol.

This is pretty distracting, and I would prefer if Waybar downsized larger logos to get a consistent height.

**Comment by jpoppe** [comment] 2022-03-07 17:46
Quick fix for `Arch` users who deleted their cache to roll back is :
```
sudo pacman -U https://archive.org/download/archlinux_pkg_waybar/waybar-0.9.9-2-x86_64.pkg.tar.zst
```

My WezTerm icon became so large it became kind of unworkable, maybe this helps some other Arch users until it is fixed upstream ;)

**Comment by Hornobster** [comment] 2022-03-07 17:47
> Quick fix for `Arch` users who deleted their cache to roll back is :
> 
> ```
> sudo pacman -U https://archive.org/download/archlinux_pkg_waybar/waybar-0.9.9-2-x86_64.pkg.tar.zst
> ```
> 
> My WezTerm icon became so large it became kind of unworkable, maybe this helps some other Arch users until it is fixed upstream ;)

You can just disable the icon altogether in the waybar config, with

```
"sway/window": {
    "icon": false
}
```

**Comment by jpoppe** [comment] 2022-03-07 17:48
> You can just disable the icon altogether in the waybar config, with
> 
> ```
> "sway/window": {
>     "icon": false
> }
> ```

Even better, thanks 👍🏻

**Comment by rieje** [comment] 2022-03-08 02:32
This is a duplicate of https://github.com/Alexays/Waybar/issues/1456.

**Comment by Alexays** [comment] 2022-03-08 08:49
Dups of #1461

**Closed by Alexays** 2022-03-08 08:49 UTC
